### ISSUE TITLE
Function invocation matchers

### ISSUE THREAD

**Issue by Grafikart** [kahlan/kahlan#150]
Method invocation matchers are really nice and easy to use. Since it's possible to monkey patch anything wouldn't it be possible to have matchers for functions.
At the moment we can use what's in place :

```php
it('should receive en email', function() {
    $called = 0;
    $args = null;
    Monkey::patch('mail', function () use (&$called, &$args) {
        $args = func_get_args();
        $called = $called + 1;
        return true;
    });
    $this->user->buy($this->item); 
    expect($called)->toBe(1);
    expect($args[0])->toBe('john@doe.fr');
});
```

But it feels quite heavy to go this way. A new matcher could simplify everything : 

```php
it('should receive en email', function() {
    // We can use the same API than Kahlan\Matcher\ToReceive
    expect('mail')->called()->with('john@doe.fr')->once();
    $this->user->buy($this->item); 
});
```

Unfortunately, I don't feel confident enough with the code base to do a PR for this.

**Comment by jails** [comment]
Would be quite handy :+1: 
Maybe I should refactor the whole logic underground toward a unique API.
I'll need to think about it but yeah a matcher can definitely make it.
I'll will keep you posted anytime soon.

**Comment by m1ome** [comment]
I think `expect('mail')` is not pretty straight-forward solution? can this lead to some collisions?

**Comment by jails** [comment]
I don't think so. With `toReceive()` `expect()` take a fully name-spaced class name as parameter. So it seems legit that for a kind of `toBeCalled()` matcher `expect()` should take fully name-spaced function name as parameter.

**Comment by m1ome** [comment]
@jails 👌

**Comment by jails** [comment]
Implemented in https://github.com/crysalead/kahlan/commit/bd662a25c9d99f4f2c7e1408810b6f415669ec27

**Comment by jails** [comment]
Available in dev branch https://github.com/crysalead/kahlan/pull/155

**Comment by jails** [comment]
Merged in master.
