### ISSUE TITLE
[RFC] Mark test as pending

### ISSUE THREAD

**Issue by ProPheT777** [kahlan/kahlan#158]
Hey, 

Today we are not able to mark a test as pending. By default empty test are marked as passed. 

It's problementic when you write all spec without writing test inside because all as marked done. 

Moreover two kind of pending system will be appriciated :

* Pending (Implementation is in progress but not finished) 
* Not supported (Implementation is planned, but not started) 

When non dev guy look at test report in verbose mode, it's easy to understand what is currently in progress and what features ares planned.

What do you think?

**Comment by jails** [comment]
Good idea.
What do you think of the following:

```php
it("is a pending spec", function() {
    // no expect inside
});

xit("is a not supported spec", function() {
    // whatever
});
```

**Comment by ProPheT777** [comment]
LGTM, still simple, I like it.

Other posibility for not supported :

```php
it("is a not supported spec", function() {
    return false;
});
```

that avoid to have non sense word "xit" in describe-it test, may be better?

**Comment by jails** [comment]
Yeah I don't really like non sense word either but the main issue is I would like to keep Kahlan as compatible as possible with Jasmine https://jasmine.github.io/2.0/introduction.html#section-Pending_Specs

However the fact that there's 3 different ways to declare pending spec in Jasmine isn't really interesting. So I think we can use `xit()` to identify a "special pending state" which is not a really a big meaning change btw.

**Comment by jails** [comment]
Available in dev branch https://github.com/crysalead/kahlan/pull/155

**Comment by jails** [comment]
Merged in master.
