### ISSUE TITLE
Wrong code coverage report

### ISSUE THREAD

**Issue by vantoozz** [kahlan/kahlan#162]
Code coverage report marks PHP7 strict types declaration as coverable string

I have a code in App/Listeners/LogError.php
```php
<?php declare(strict_types = 1);

namespace App\Listeners;

...
```
I run test suite with coverage (--coverage=3 --clover=clover.xml)

_Expected result:_
clover.xml **contains no**
```xml
<file name="/App/Listeners/LogError.php">
      <line num="1" type="stmt" count="0"/>
</file>
```

_Actual result:_
clover.xml **contains**
```xml
<file name="/App/Listeners/LogError.php">
      <line num="1" type="stmt" count="0"/>
</file>
```

**Comment by jails** [comment]
Thanks for the detailed report, fixed in https://github.com/kahlan/kahlan/commit/6758ea6f30c7ada7babadce571258d2b9d42e088
