### ISSUE TITLE
Add toImplement() matcher

### ISSUE THREAD

**Issue by jasonmccreary** [kahlan/kahlan#165]
What do you think about implementing a `toImplement` matcher? This would be handy rather than having to use [`class_implements()`](http://php.net/manual/en/function.class-implements.php) directly and seems to be inline with `toBeAnInstanceOf()` style matchers.

**Comment by jails** [comment]
Good idea. Should we support array as argument ?
```php
expect($something)->toImplement(['Interface1', 'Interface2'])
```
or simply:
```php
expect($something)->toImplement('Interface1');
expect($something)->toImplement('Interface2');
```

**Comment by jasonmccreary** [comment]
I vote the second. Nice and simple.

**Comment by jasonmccreary** [comment]
I'm glad to add it. I just wanted to make the first issue… 😜

**Comment by jails** [comment]
Awesome :+1:
Feel free to ping me if you need any help !

**Comment by jasonmccreary** [comment]
According the comments in the PHP manual, you can test this via `instanceof`. As such, `expect($obj)->toBeInstanceOf('class')` does *work*.

Nonetheless, I still think I'll add it for clarity of matchers and to get more familiar with the codebase. However, going to finish the Kahlan docs first.

**Comment by jails** [comment]
Interesting, so an alias should be enough :+1:

**Comment by jails** [comment]
Let's move it as an extra matcher for now https://github.com/kahlan/extra-matcher
