### ISSUE TITLE
Monkey patch class properties

### ISSUE THREAD

**Issue by crissi** [kahlan/kahlan#178]
Would you consider adding something like this?

EX:
allow('MyGlobalDBModel::class')->toHaveProperty('server' => 'global_test');

Which will set the property of the class to the chosen one before being called.

In my usecase I have a customer pr db, and a global server which all customers fetch data from.

During testing I want this db model that normally fetches from a global db server named: "global" to fetch from "global_test" instead.

**Comment by jails** [comment]
Imo environment variables are the way to go here.
If you can't really bootstrap your test environment through your `kahlan-config.php` file with some test connections, you can also use `'KAHLAN_VERSION'` like so:

```php
if (defined('KAHLAN_VERSION')) {
    // set your global connection for the test env
} else {
    // set your global connection as usual
}
```
