### ISSUE TITLE
PHP Fatal error:  Call to undefined function allow()

### ISSUE THREAD

**Issue by noren** [kahlan/kahlan#179]
Hi,

I'm trying to monkey path php Redis class as follow:

`allow('\Redis')->toReceive('exists')->andReturn([false]);`

Redis class is instantiated in the constructor of the class I'm trying to test, similar to the example from the current documentation @ 'https://kahlan.github.io/docs/allow.html' mocking PDO

but I get 

`PHP Fatal error:  Call to undefined function allow()`

It looks like 'allow' method don't exist what was the older syntax to monkey path 
class instantiated in constructor?

Thanks

**Comment by samsonasik** [comment]
what kahlan version you use? do you use `kahlan/kahlan: ^3.0` ? it seems your issue is about `allow()` autoloading. 

It working as expected in my repositories: 
- https://github.com/sitrunlab/learn-kahlan/blob/master/spec/FooSpec.php#L43-L45
- https://github.com/samsonasik/ApigilityConsumer/blob/master/spec/Service/ClientServiceSpec.php#L80

**Comment by jails** [comment]
It's not possible with the 2.x directly, so I strongly recommend you to upgrade to 3.x.
The only alternative was to use a double and inject it like so:

```php
it("stubs overrided PHP core method", function() {

    $redis = Stub::create(['extends' => 'Redis', 'layer' => true]);
    Stub::on($redis)->method('connect')->andReturn('stubbed');
    expect($stub->connect('127.0.0.1'))->toBe('stubbed'); //It passes

});
```

The full 2.x documentation https://github.com/kahlan/kahlan/tree/2.5.8/docs

**Comment by noren** [comment]
I'm version using 2.5.3; I will use dependency injection instead, thanks

**Comment by noren** [comment]
Following your example: 

```
$redis = Stub::create(['extends' => 'Redis', 'layer' => true]);
Stub::on($redis)->method('connect')->andReturn('stubbed');
expect($redis->connect('127.0.0.1'))->toBe('stubbed'); 
```
@ https://github.com/kahlan/kahlan/blob/2.5.8/docs/stubs.md#class-stubbing

I'm getting following PHP ERROR:

`PHP Parse error:  syntax error, unexpected 'echo' (T_ECHO), expecting identifier (T_STRING) in /app/common/vendor/crysalead/kahlan/src/Plugin/Stub.php(226) : eval()'d code on line 12`

I'm unable to create Redis stub either way.

Any ideas ?

**Comment by jails** [comment]
Looks like Redis use `echo` as method name which is not allowed by PHP (`echo` is part of reserved keywords http://php.net/manual/en/reserved.keywords.php)... don't know how they were able to do that btw.

So just stub what you need:

```php
$redis = Stub::create(['extends' => 'Redis', 'methods' => ['exists']);
Stub::on($redis)->method('exists')->andReturn('false');
expect($redis->exists())->toBe(false); 
```

**Comment by samsonasik** [comment]
I tried and working fine, your spec should be like the following:

```php
namespace App\Spec;

use Kahlan\Plugin\Stub;

describe('REDIS', function () {

    describe('connect', function () {
        
        it("redis connected", function() {

            $redis = Stub::create(['extends' => 'Redis', 'layer' => true]);
            Stub::on($redis)->method('connect')->andReturn('stubbed');
            expect($redis->connect('127.0.0.1'))->toBe('stubbed');
            
        });
        
    });
    
});
```

**Comment by samsonasik** [comment]
I created repository https://github.com/samsonasik/kahlan-issue-question179 and working fine ;), please clone and try yourself : `composer install && bin/kahlan` ;)

**Comment by noren** [comment]
I was using 

`
"crysalead/kahlan": "dev-master"
`

in my composer file, after changing it to 

`"kahlan/kahlan": "2.5.8"` 


@jails example seems to work now, but on @samsonasik branch is still throwing same error,

I'm using php version 5.6.8 btw.

Thanks, for your help!

**Comment by jails** [comment]
Indeed you'll need to update to PHP7.0 to take benefit from https://wiki.php.net/rfc/context_sensitive_lexer which allow semi-reserved words as method name.
