### ISSUE TITLE
disable phpcs check in hhvm for travis

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#180]
travis keep failing for hhvm when running phpcs, is it ok to skip the cs check for hhvm? alternative: or use another tool for it ( phpcsfixer or service like styleCI )

**Comment by jails** [comment]
Well, phpcs just display a couple of warning but it doesn't really break the build. The issue is HHVM >= 3.10 is segfaulting on declare statements. In theory the issue has been solved https://github.com/facebook/hhvm/issues/7297, we just need to wait the fix to be included in a tagged version.

**Comment by samsonasik** [comment]
ok :+1:
