### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by tyranron** [kahlan/kahlan#182]
Is here anybody interested in packing Kahlan into Docker image to be able to use it in manner of [official `php-cli` image](https://hub.docker.com/r/library/php)?

We can also pack phpdbg or Xdebug into image.

Possible issues (or challenges?) are:
* PHP extensions. Different applications may require different ones, but official PHP images provide only few. It's quite uncomfortable for every project write its own `Dockerfile` basing on official Kahlan image just because couple extensions are missing. And packing into image all possible PHP extensions is also strange idea.
* Container fs layout. We are used to run Kahlan in `vendor/bin/kahlan` manner which supposes having Kahlan sources in `vendor` dir. That's not playing well with idea of having Kahlan as preinstalled tool inside container.

**Comment by jails** [comment]
I'm not using Docker personally but it's a good idea :+1: 
Willing doing it ?

**Comment by Kaijiro** [comment]
That's would be a nice idea.

For the PHP extensions problem, maybe a first solution would be to use PEAR and/or PECL as it has +600 PHP packages ready to install ([complete list here](http://pear.php.net/packages.php)) for the first one and +300 for PECL ([list](https://pecl.php.net/packages.php))

We should be able to manage PHP versions too I think as many Web Applications has not yet been "translated" from PHP5 to PHP7. I recently found an application allowing to manager PHP versions & builds, it is named [PHPBrew](https://github.com/phpbrew/phpbrew)

**Comment by tyranron** [comment]
@Kaijiro the problem is not where to get extensions. There is convenient way of [installing extensions for official PHP docker image](https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions). The problem is to minimise (ideally remove) the need of image users to build new images on top of our Kahlan image, and satisfy their needs out-of-the-box as much as possible. If not, there is no much need in such Kahlan official image, cause everybody will build its own one anyway.

@jails can try. But, definitely, would like to hear more thoughts and opinions related to desrbed issues. 'Cause don't see elegant solution at the moment.

**Comment by Kaijiro** [comment]
@tyranron Yup, I understand this, but I was thinking at something like the image user pass as argument the list of PHP extension he wants to install / enable and maybe we should create a small script to install those extension, what do you think ?

**Comment by jails** [comment]
I think the best we can do is the following https://github.com/JulienBreux/phpspec-docker

**Comment by tyranron** [comment]
@Kaijiro yes, we can. But extensions installation is not fast. Often it requires to compile C/C++ sources. Having this process on every container start will definitely give a rage to someone =) Extensions must be installed at build-time, not run-time.

@jails thank you for pointing me. As far as I see, `phpspec` image is build `FROM composer/composer` image, and that one includes [following extensions](https://hub.docker.com/r/composer/composer/~/dockerfile/). And looking through issues of that repos, it seems that people don't have troubles with extensions in common.
I agree to start with similar `Dockerfile`.

**Comment by jails** [comment]
Isn't:
```
RUN docker-php-ext-install <myextension>
```
is the way to go to install custom extension if necessary ?

**Comment by tyranron** [comment]
@jails yes. But for doing it user should create its own `Dockefile` using `FROM kahlan/kahlan` and then paste `RUN docker-php-ext-install <desired-extension>`. Then user must build new image from that `Dockerfile` and now he can use it.
My point is to minimise situations where users should build their own images as much as possible. 'Cause if everybody needs to build its own image every time he wants use kahlan - what is the point in official image if he needs to write own `Dockerfile` anyway?

**Comment by Kaijiro** [comment]
Even if we minimize this case, it will happens sometimes, we can not avoid it

**Comment by tyranron** [comment]
For Kahlan Docker image repository [kahlan/docker-image](https://github.com/kahlan/docker-image) is created.
Here is [things to be done](https://github.com/kahlan/docker-image/issues/1) before deploy image to Dockerhub.

Returning to a question about extensions, I decided to start with those provided by [Composer Docker image](https://hub.docker.com/r/composer/composer/~/dockerfile/) as far as our image is built on top of that one (similar to [phpspec-docker](https://github.com/JulienBreux/phpspec-docker)). More extensions can be added lately if they will be really required.

There will be bunch of images for reason to support:
* both `2.5.x` and `3.0.x` versions of Kahlan
* both `php7` and `php5`
* both `alpine` and `debian` based container versions

Planning to automate builds, so variety of versions should not make a big pain.

I'm closing this issue. All discussions related to Kahlan Docker image is better to continue [there](https://github.com/kahlan/docker-image/issues).
