### ISSUE TITLE
setup spec directory via kahlan kahlan-config.php

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#184]
Hi @jails , we have `--spec=dirspec` in kahlan command, is there any way to specify directory via kahlan-config.php ?

**Comment by LostKobrakai** [comment]
It's even mentioned in the docs, even if not for the spec argument: https://kahlan.github.io/docs/config-file.html
```php
$commandLine = $this->commandLine();
$commandLine->argument('spec', 'default', 'somedir');
```

**Comment by samsonasik** [comment]
@LostKobrakai Thank you, it seems for kahlan v3, the `argument()` should be `option()`, I think documentation should be updated.

**Comment by samsonasik** [comment]
I created PR for change `argument()` to `option()` for CommandLine set option: https://github.com/kahlan/docs/pull/6

**Comment by jails** [comment]
Merged in the docs repo !
