### ISSUE TITLE
test Throwable

### ISSUE THREAD

**Issue by fzed51** [kahlan/kahlan#188]
Bonjour,
je rencontre un problème pour tester directement un Throwable dans PHP7.
Pour l'instant, j'y arrive en modifiant le matcher "toThrow". Dans la méthode "actual", j'ajoute :
```php
catch (Throwable $t) {
    return $t;
}
```
(testé aussi en PHP5 et ça ne retourne pas d'erreur)
dans mes spec je peux tester ça :
```php
expect(function(){Session::addModule(new notModule());})->toThrow(new \TypeError());
```

ça fonctionne bien mais je ne suis pas satisfait.

---- Google translate ----

Hello,
I encounter a problem to directly test a throwable in PHP7.
For now, I get by modifying the matcher "toThrow". In "actual" method, I add:
```php
catch (Throwable $t) {
    return $t;
}
```
(Also tested in PHP5 and it does not return an error)
my spec I can test it:
```php
expect(function(){Session::addModule(new notModule());})->toThrow(new \TypeError());
```

it works well but I'm not satisfied.

**Comment by jails** [comment]
Thanks for the head up, should be fixed in the dev branch https://github.com/kahlan/kahlan/commit/ececbfc013f80f237ed16246e8c7cc5df3ee240b
