### ISSUE TITLE
Mock a Datetime failed

### ISSUE THREAD

**Issue by piolet** [kahlan/kahlan#189]
When i try to mock a DateTime, with this code :
`allow('\DateTime')->toBe(new \DateTime('2016-10-28 12:14:27'));`

I always get the current date, and my unit test failed. It's not funny ;)

My sample code is like this :
```
$product = new Product();
$params = $product->to_array();
allow('\DateTime')->toBe(new \DateTime('2016-10-28 12:14:27'));
expect(count($params))->toBe(19);
expect(...);
expect($params["PROFILESTARTDATE"])->toBe("2016-11-28T12:14:27+02:00");
```

My Product class is in a specific namespace, and in my "to_array" method, i have this piece of code, to construct my date :

```
namespace My\Name\Space;
...
class Product {
 public function to_array() {
  ...
  $date_tmp = new \DateTime();
  $my_date= $date_tmp->add(new \DateInterval($interval))->getTimestamp();
 }
}
```

**Comment by jails** [comment]
Looks like it's working: https://travis-ci.org/jails/temp
Make sure your class is loaded by composer (i.e. not through a `require` statement).
Or create a repo with a failing spec so I can investigate.

**Comment by piolet** [comment]
i've add this test, to test :
```
      allow('DateTime')->toBe(new \DateTime('@123'));
      expect(count($params))->toBe(19);
      $datetime = new \DateTime();
      expect($datetime->getTimestamp())->toBe(123);
``` 

But failed too. (without Object or namespace) :/

**Comment by jails** [comment]
Use the working repo above to reproduce your issue.
Problems generally rely on unshowed part of code.

**Comment by piolet** [comment]
I'll test this tonight

**Comment by piolet** [comment]
hey, in French, it is called the "boulet time" (not "bullet time" ;) ).
It's entirely my fault. I was doing my "allow" after calling the function to be tested, so obviously no effect.

Really sorry for the inconvenience.

**Comment by jails** [comment]
Glad you find your issue :+1:

**Comment by piolet** [comment]
👍
