### ISSUE TITLE
beforeAll() hide error stub error, given() show it

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#190]
for a class that need to be mocked with apply dependency ( eg: in `X::__construct(Dependency $d)` ), with beforeAll():

```php
beforeAll(function() {
   $x   = Double::instance(['extends' => X::class]);
   $this->foo = new Foo($x);
}
```
It doesn't show any error, but when call `echo $?` after `bin/kahlan` executed, it got `255` error.

Trying with `given()`, it got error:
```
`TypeError` Code(0) with message "Argument 1 passed to X::__construct() must be an instance of Dependency, none given, called in vendor/kahlan/kahlan/src/Plugin/Double.php on line 62"
```
So, then I change to:

```php
given('foo', function() {
   $x = Double::instance(['extends' => X::class, 'methods' => '__construct']);
   return new Foo($x); 
}
```

The issue is, on `beforeAll()`, it doesn't show verbose error while at `given()`, it show the verbose error.

**Comment by jails** [comment]
Would you mind testing it on the [temp](https://github.com/kahlan/kahlan/tree/temp) branch to check if it hasn't been solved there ?

**Comment by samsonasik** [comment]
I tested [temp](https://github.com/kahlan/kahlan/tree/temp) branch and it fixed the issue. Now I got the expected verbose error.

Thank you.
