### ISSUE TITLE
test reporter

### ISSUE THREAD

**Issue by eugene-matvejev** [kahlan/kahlan#191]
hi guys,

thanks for test framework, but i think I found a bug, please observe output below (20% two times, and I think 20% is not correct number, as 80/299 !== 20% :)

```
BUILD SUCCESSFUL
Total time: 3 seconds
>>> λ: bin/kahlan 
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The Unit/BDD PHP Test Framework for Freedom, Truth, and Justice.

Working Directory: /Users/Eugene/prototype/battleship-game-api

................................................................................ 0%
................................................................................ 20%
................................................................................ 20%
...........................................................                      100%

Executed 299 of 299 PASS in 0.115 seconds 
```

you can check code:
https://github.com/eugene-matvejev/battleship-game-api

you can launch code via __ant test__

**Comment by LostKobrakai** [comment]
I'd imagine that because the percentage is the percentage of tests completed, while the dots are one for each `expect()…` which is run.

**Comment by jails** [comment]
@LostKobrakai is right, the percent is build on executed `it()` while dots represent an `expect()` result. I recognize it's not really consistent but the issue has been fixed in the 3.x version.
