### ISSUE TITLE
Integer vs Double without conversion

### ISSUE THREAD

**Issue by Kaijiro** [kahlan/kahlan#193]
Hey,

I think this is a bit PHP's "mistake" there but I think we can maybe do something. 
Let's suppose I'm generating 3 totally random values and I am calculating the average of the 3. I may have a double BUT I may have an integer (ex.: with ((3 + 6 + 9) / 3 => 18 / 3 => 6).

Maybe something like a strict mode on the `toBeA()` and `toBeAn()` matcher could be something interesting to implement.

Let me know of what you think about this idea

**Comment by samsonasik** [comment]
I think that new kind of matcher should be at https://github.com/kahlan/extra-matcher

**Comment by jails** [comment]
Not sure to get what you mean ` toBeA()` and `toBeAn()` are already strict matchers no ?

**Comment by Kaijiro** [comment]
Yes they are, and this is what is the problem in my example. Maybe we could add a strict mode, enabled by default, and with a boolean passed to the matcher or inside the config.

Or, an other solution would be to create an "or" operator so we could do something like
```php
expect($myVar)
    ->toBeA("double)
    ->or->toBeAn("integer");
```

**Comment by jails** [comment]
Oh I see, well I don't think it'll be a good idea. A good testing practice is to test the code behavior instead of its implementation.

So if the return value can be either a `double` or an `integer` both of them should be tested separately as two different behaviors.

```php
it("works when the result is a double", function() {
    ...
    expect($myVar)->toBeA("double");
    ...
});
it("works when the result is an integer", function() {
    ...
    expect($myVar)->toBeA("integer");
    ...
});
```
But imo the best solution here is to cast the return value upfront to always be a `double` to avoid "potential" side effects.

**Comment by Kaijiro** [comment]
Hmm yep you're right. Maybe what I was asking for will be more a source of problems than a simple solutions. 
Now that the week-end passed, I am looking at the problem with a fresh eye ; and obviously, the problem here is the implementation of what I did.

Thank you for your time ;)
