### ISSUE TITLE
Cannot test a class constant

### ISSUE THREAD

**Issue by NoMan2000** [kahlan/kahlan#194]
The following test will fail.  

	class ClassConstantOne
	{
	    const CONSTANT_ONE = 1;
	}

	class ClassConstantTwo extends ClassConstantOne
	{
	    const CONSTANT_ONE = 'one';
	}

	define("A class constant can be overridden by another class", function () {
	    
	    it("Can override a class constant, but not an interface constant", function () {
	
	        expect(ClassConstantOne::CONSTANT_ONE)->toBe(1);
	        expect(ClassConstantTwo::CONSTANT_ONE)->toBe('one');
	    });
	});

If you want to test that is a valid assertion:

    assert(ClassConstantOne::CONSTANT_ONE === 1, "Can override a class constant, but not an interface constant");
    assert(ClassConstantTwo::CONSTANT_ONE === 'one', "Can override a class constant, but not an interface constant");

The error message is:

>   [RuntimeException]                                                           
>   Error Output: PHP Warning:  Constants may only evaluate to scalar values or  
>    arrays in /Users/michaelsoileau/Sites/oopPHP/public/spec/ChapterThree/Clas  
>   sConstants.spec.php on line 15                                               
> 
>   PHP Stack trace:                                                             
>   PHP   1. {main}() /Users/michaelsoileau/Sites/oopPHP/vendor/kahlan/kahlan/b  
>   in/kahlan:0                                                                  
>   PHP   2. Kahlan\Cli\Kahlan->run() /Users/michaelsoileau/Sites/oopPHP/vendor  
>   /kahlan/kahlan/bin/kahlan:47                                                 
>   PHP   3. Kahlan\Filter\Filter::on() /Users/michaelsoileau/Sites/oopPHP/vend  
>   or/kahlan/kahlan/src/Cli/Kahlan.php:370                                      
>   PHP   4. call_user_func_array:{/Users/michaelsoileau/Sites/oopPHP/vendor/ka  
>   hlan/kahlan/src/Filter/Filter.php:213}() /Users/michaelsoileau/Sites/oopPHP  
>   /vendor/kahlan/kahlan/src/Filter/Filter.php:213                              
>   PHP   5. Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}() /Users/michaelsoileau/Si  
>   tes/oopPHP/vendor/kahlan/kahlan/src/Filter/Filter.php:213                    
>   PHP   6. Kahlan\Cli\Kahlan->_load() /Users/michaelsoileau/Sites/oopPHP/vend  
>   or/kahlan/kahlan/src/Cli/Kahlan.php:357                                      
>   PHP   7. Kahlan\Filter\Filter::on() /Users/michaelsoileau/Sites/oopPHP/vend  
>   or/kahlan/kahlan/src/Cli/Kahlan.php:469                                      
>   PHP   8. call_user_func_array:{/Users/michaelsoileau/Sites/oopPHP/vendor/ka  
>   hlan/kahlan/src/Filter/Filter.php:213}() /Users/michaelsoileau/Sites/oopPHP  
>   /vendor/kahlan/kahlan/src/Filter/Filter.php:213                              
>   PHP   9. Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}() /Users/michaelsoileau/Si  
>   tes/oopPHP/vendor/kahlan/kahlan/src/Filter/Filter.php:213                    
>   PHP  10. require() /Users/michaelsoileau/Sites/oopPHP/vendor/kahlan/kahlan/  
>   src/Cli/Kahlan.php:467                                                       
>   PHP  11. define() /Users/michaelsoileau/Sites/oopPHP/public/spec/ChapterThr  
>   ee/ClassConstants.spec.php:15

**Comment by jails** [comment]
Not sure to get what you mean. I tested the [following code](https://github.com/jails/temp/commit/c4dcb9f92579e85f8f9e0deadbc2e985486c15df). And [specs passed](https://travis-ci.org/jails/temp). Feel free to clone https://github.com/jails/temp to provide a full working/unworking example of the above issue so I can investigate.

**Comment by NoMan2000** [comment]
I should have added three pieces:

    PHP 7.0.12
    error_reporting => 32767 => 32767
    Kahlan 3.0.2

But I cloned your repo and with errors on, had no problem, but it failed in my main one.  I'm guessing something else is interfering, so closing out this issue.
