### ISSUE TITLE
REST Calls inside test case

### ISSUE THREAD

**Issue by Kaijiro** [kahlan/kahlan#195]
Hey,

I'm building some mocks for an API and inside my spec files, I'm on building a REST Client (with tcdent/php-restclient library).

The problem is that inside my spec file (the only one I tested now) only the first `it` works, the other ones acts like if the client wasn't initialized. When I comment the first test case, the second one works, when I comment the first and the second, the third works, etc ...

Any idea ?

**Comment by samsonasik** [comment]
have you tried `beforeAll(function()` for initialization? for current 3.0.2, you should get a verbose error with `given('string-name-property', function()` that return specific object.

**Comment by Kaijiro** [comment]
Same problem that with the `given()`, the first test pass then the others fail

**Comment by samsonasik** [comment]
could you provide sample code test?

**Comment by Kaijiro** [comment]
I created [this repo](https://github.com/Kaijiro/kahlan-test) for testing

**Comment by samsonasik** [comment]
I tried your repo, and here my investigation:
**1**. you are missing `$this->productsMock` defintion:
```php
        $this->productMock = new productsMock();
```
in `beforeAll(function(){`
**2** moving the `productMock` to `given`, got `class not found` error, so, it is a autoload issue:
```php
   // client property
    given('client', function(){
        $sdkParams = [
            'format' => 'json',
            'headers' => [
                'Content-Type' => 'application/json'
            ]
        ];

        return new \RestClient($sdkParams);
    });
    // productMock property
    given('productMock', function () {
        return new \EServicial\Mocks\ProductsMock();
    });
```
**3** modifying the psr-4 autoload and composer dump-autoload
```
    "autoload" : {
        "psr-4": {
            "EServicial\\": "src/Test/"
        }
    },
    "autoload-dev": {
        "psr-4": {
             "EServicial\\Spec\\": "spec/"
        }
    }
```
**3** run vendor/bin/kahlan got :
```
Coverage Summary
----------------
                                           Lines             %

 \                                        31 / 174      17.82%
├── ()                                     0 / 104       0.00%
└── EServicial\                           30 /  69      43.48%
   └── Mocks\                             30 /  69      43.48%
      └── ProductsMock                    30 /  69      43.48%
         ├── ProductsMock::findAll()      30 /  41      73.17%
         └── ProductsMock::findOne()       0 /  28       0.00%

Total: 17.82% (31/174)
```
even still error, the `productMock` itself already detected.

That's it ;), I hope it help you fix the issue ;)

**Comment by samsonasik** [comment]
I created PR https://github.com/Kaijiro/kahlan-test/pull/1 to your repo to help investigate it.

**Comment by Kaijiro** [comment]
Thank you, but there are a few mistakes / misunderstanding :

- What I'm going right now is to get rid of ProductsMock direct and use my rest client to reach my mock through the router initialized in `index.php`
- I made a few mistake with namespaces and a last ProductsMock object direct call.

I created this repo very quickly, it's only a small part of my complete project

**Comment by samsonasik** [comment]
you can use `Kahlan\Plugin\Double`

**Comment by Kaijiro** [comment]
Uuuh ? Why ?

**Comment by samsonasik** [comment]
I can understand, unfortunatelly, your repository is not reproduceable on mine, what I can propose is giving a try with one of these:
```
beforeEach(function() { $this->varname = new YourObject(); }
beforeAll(function() {  $this->varname = new YourObject(); }
given('varname', function() { return new YourObject(); }
```

**Comment by jails** [comment]
@Kaijiro you can't use multiple `require_once` that way. The second time your require the same file it simply returns `true`.

You can either [inject the `$config` variable in root scope](https://kahlan.github.io/docs/pro-tips.html) or simply:

```php
beforeAll(function(){
    $this->config = include(__DIR__ . '/../src/Test/Config/config_test.php');
});
```
and use `$this->config` in specs.

**Comment by Kaijiro** [comment]
Holy crap, my mistake is sooooo stupid that I and @samsonasik didn't notice it ....

Thank you @jails
