### ISSUE TITLE
Shared behaviour (describe-it blocks reusing)

### ISSUE THREAD

**Issue by tyranron** [kahlan/kahlan#196]
What do you think about having kinda of [RSpec shared examples](https://www.relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples)?
It will allow to reuse `describe`, `context` and `it` blocks, which seems to be a rarely case (as far as nobody has asked for it yet), but still happens often enough.

It may be something like (please, do not get naming seriously):
```php
behaviour('no authorization performed', function () {
    it('does not authorize user', function () {
        $auth = (new Authorization($this->params))->run();
        expect($auth->getUser())->toBeNull();
    });
});

context('when no authorization token is specified', function () {
    beforeAll(function () {
        $this->params = [];
    });
    behaves('no authorization performed');
});

context('when invalid authorization token is specified', function () {
    beforeAll(function () {
        $this->params = ['token' => 'invalid'];
    });
    behaves('no authorization performed');
});
```

It's not a something critical, and usually such situations are easily resolved (via specs restructuring, or simple copy-paste). But, maybe, it can be useful?

**Comment by jails** [comment]
Interesting but why not simply:

```php
function expect_no_authorization_performed() {
    it('does not authorize user', function () {
        $auth = (new Authorization($this->params))->run();
        expect($auth->getUser())->toBeNull();
    });
});

context('when no authorization token is specified', function () {
    beforeAll(function () {
        $this->params = [];
    });
    expect_no_authorization_performed();
});

context('when invalid authorization token is specified', function () {
    beforeAll(function () {
        $this->params = ['token' => 'invalid'];
    });
    expect_no_authorization_performed();
});
```

**Comment by tyranron** [comment]
Actually, nothing. This is a "workhorse" solution.

But that approach has following downsides:
-  Namespace. Once declared `expect_no_authorization_performed()` cannot be redeclared. For different files it is solved with different namespaces. But for using it in the same file, it makes us to invent another name, even if it's used in entirely different contexts. And adding yet another word just to avoid names collision can make specs readability worse.
    ```php
    context('users', function () {
        function expect_no_authorization_performed() {
            it('does not authorize user', function () {
                $auth = (new User\Authorization($this->params))->run();
                expect($auth->getUser())->toBeNull();
            });
        }
    });
    context('applications', function () {
        function expect_no_authorization_performed() {  // Oops! We need another name here!
            it('does not authorize application', function () {
                $auth = (new Application\Authorization($this->params))->run();
                expect($auth->getApplication())->toBeNull();
            });
        }
    });
    ```
- Aesthetic & readability. Reading specs our eye is used to distinguish specs declaration and actual testing code quite well, mainly, due to nice Kahlan DSL. Seeing DSL statement we unconsciously expect a spec declaration there. Seeing a common function among DSL statements can confuse us for a while, like `...stop! wut? o.O`.

But, I am really not sure, that fixing those downsides will worth Kahlan DSL complication.

**Comment by jails** [comment]
Fair enough!
So I'll leave that issue open to gather ideas about what we should do since the Rspec way doesn't sounds right.

**Comment by jails** [comment]
Let's close this since I have no idea of what should be the best option here.
Better to create new issues when better ideas will pop out.
