### ISSUE TITLE
Atom extension

### ISSUE THREAD

**Issue by PurpleBabar** [kahlan/kahlan#197]
Hi guys i created yesterday an Atom extension which for the moment does only autocomplete for Kahlan basic functionnalities :)
If you want to take a look at it :)

https://github.com/elephantly/atom-kahlan

**Comment by jails** [comment]
Hey that's really nice :+1: 
Thanks for head up !!

**Comment by samsonasik** [comment]
@PurpleBabar could you send PR to kahlan/docs for it https://github.com/kahlan/docs/blob/master/integration.md , Thanks ;)

**Comment by PurpleBabar** [comment]
Hey :) With pleasure :) i'll do it in the day :)
