### ISSUE TITLE
merge 'temp' to 'dev'

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#199]
on issue #190, the 'temp' branch fixes the `given` vs `beforeAll` verbose issue. @jails any plan to merge temp to dev ?

**Comment by jails** [comment]
I introduced a couple of Break BC in the `temp` branch so I don't think I'll be able to merge it before the 4.0 version

**Comment by samsonasik** [comment]
probably create a branch named '4.x' so make more verbose ?

**Comment by jails** [comment]
It's gonna happen anytime soon ;-)

**Comment by samsonasik** [comment]
👍
