### ISSUE TITLE
Symfony KahlanBundle

### ISSUE THREAD

**Issue by Tiriel** [kahlan/kahlan#201]
Hello there!

Just to let you know I love this framework, so I've worked-out a small KahlanBundle for Symfony.
Here are the links:
https://github.com/elephantly/kahlan-bundle
https://packagist.org/packages/elephantly/kahlan-bundle

It's functionnal, integrated in Symfony's command system, automatically loads container, has shortcuts for services, and provides a service to instanciate Request objects if you need them to test particular functions.

Currently working on doc and around a little snag I have encountered.

Hope you like it!

**Comment by Tiriel** [comment]
**Edit:** Issue marked on the repo doesn't seem to be an issue with the bundle after all, and documentation is now more complete.

**Comment by samsonasik** [comment]
could you send a PR into kahlan/docs? I think this can be added to https://github.com/kahlan/docs/blob/master/integration.md with basic usage.

**Comment by jails** [comment]
That's really cool @Tiriel, good job :+1: !
Yeah this could definitely be added in the documentation.
