### ISSUE TITLE
minimum php version required, 5.4 or 5.5 ?

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#205]
in README.md, it says:
```
Requirements

    PHP 5.5+
```
but in composer.json, it says:
```
    "require": {
        "php": ">=5.4"
},
```

**Comment by jails** [comment]
Composer is right https://travis-ci.org/kahlan/kahlan ;-)

**Comment by samsonasik** [comment]
Thanks, I updated readme https://github.com/kahlan/kahlan/commit/fb20e5b004201b537083d6572f06318ad7437250

**Comment by jails** [comment]
:+1:
