### ISSUE TITLE
Call to undefined method Kahlan\Matcher\ToReceive::andReturn

### ISSUE THREAD

**Issue by mbm-rafal** [kahlan/kahlan#210]
Regarding to https://kahlan.github.io/docs/matchers.html at Method invocation matchers executing code: 

```
describe('GenericListingManager', function() {
    using(['database transactions'], function() {
        it('adds items to list', function() {

            $listing = factory(Listing::class)->create();
            $manager = new ListingManager($listing);

            $item  = factory(ListingItem::class)->make(['listing_id' => null]);
            $item2 = factory(ListingItem::class)->make(['listing_id' => null]);
            $item3 = factory(ListingItem::class)->make(['listing_id' => null]);

            expect($manager)->toReceive('validate')->with($item2);
            expect($item2)->toReceive('save')->andReturn(true);
            expect($item3)->toReceive('save');

            $manager->addItem($item2);
            $manager->addItem($item3);

            expect($listing->items->map(function($i) { return $i->id; })->toArray())
                // ->toBeAnInstanceOf('array')
                ->toBeA('array')
                ->toHaveLength(2)
                ->toContain($item2->id);
        });

    });

    it('disallows to add duplicates', function() {

    });

});
```

produces:

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Kahlan\Matcher\ToReceive::andReturn()
```

**Comment by samsonasik** [comment]
use `allow()` instead

**Comment by LostKobrakai** [comment]
It's still either incorrect in the docs or this is a bug. 

It does feels inconvenient having to split up things like so, but on the other hand this way the expectation is more explicitly defined. Not sure how it was intended to work.
```php
allow($instance)->toReceive('method')->andReturn(true);
expect($instance)->toReceive('method')->once();
// vs.
expect($instance)->toReceive('method')->andReturn(true)->once();
```
The latter could be understood as: expecting the method to return true, instead of making it return   true.

**Comment by mbm-rafal** [comment]
@LostKobrakai Yes. Actually That is what I need. To check expectation for method's return. I do not want to make w dummy stub. 

Does anyone can tell is that a bug or doc invalidation ?

**Comment by LostKobrakai** [comment]
Afaik specification tests should not be concerned with the implementation of a feature, but rather with it's external outcome. So testing a function's return value inside the feature you're currently testing is kinda against that. If you really want to test the return value of that specific function rather use a own test spec for that. In your case this would be named something like: `it('can be saved', function(){ … });`. But that's probably not what you want to do.

In your example test it's not really the concern of the test to make sure that `$manager->addItem();` somewhere in it's execution does get a return value of `true` when issueing the `$item->save()`, but it's the concern of your `addItem()` function to fail in an observable way if that's not the case. So for that rather test if `addItem()` does throw an error if the save does fail instead. 

```php
describe('GenericListingManager', function() {
  using(['database transactions'], function() {
    […]
    
    it('does throw if items are not saved successfully', function() {

      $callback = function() {
        $listing = factory(Listing::class)->create();
        $manager = new ListingManager($listing);

        $item  = factory(ListingItem::class)->make(['listing_id' => null]);
        $item2 = factory(ListingItem::class)->make(['listing_id' => null]);

        allow($item2)->toReceive('save')->andReturn(false);

        $manager->addItem($item2);
      }

      expect($callback)->toThrow(…)
    });

  });

});
```

**Comment by mbm-rafal** [comment]
@LostKobrakai  
I'm taking up testing skills. Actually I think you're right. I'm really trying to feel about testing behavioral vs feature because this example that you provided could be tested like this as well right: 


```
it('adds items to list', function() {

            $listing = factory(Listing::class)->create();
            $manager = new ListingManager($listing);

            $item2 = factory(ListingItem::class)->make(['listing_id' => null, 'resource_id' => 2]);
            $item3 = factory(ListingItem::class)->make(['listing_id' => null, 'resource_id' => 3]);

            $manager->addItem($item2);
            $manager->addItem($item3);

            expect($listing->items->map(function($i) { return $i->id; })->toArray())
                // ->toBeAnInstanceOf('array')
                ->toBeA('array')
                ->toHaveLength(2)
                ->toContain($item2->id);
        });
```

**Comment by samsonasik** [comment]
It is doc's that incorrect, I've fixed the docs at https://github.com/kahlan/docs/commit/93e818ba88cdc3a06696b9536283ffb78e8c25ea .

Please close this issue if that fixes it ;), Thank you.

**Comment by mbm-rafal** [comment]
Thank y'all
