### ISSUE TITLE
Wrong coverage with alternate control structures

### ISSUE THREAD

**Issue by kilbiller** [kahlan/kahlan#211]
Hello and Happy New Year !

First of all, thank you very much for kahlan. Coming from a javascript background I feel right at home.
I don't know if this problem is due to kahlan or xdebug but when using PHP alternate control structures (if...endif, foreach...endforeach) end tags are not covered.

Example: 
![capture](https://cloud.githubusercontent.com/assets/3019848/21615197/b004afb4-d1dc-11e6-9c9a-0e38b48123c8.PNG)

Feel free to close this if this has nothing to do with kahlan.

**Comment by samsonasik** [comment]
I got same issue, it seems following parser token need to be registered at `Kahlan\JIT\Parser`:
```php
    case T_ENDIF:
    case T_ENDFOREACH:
    case T_ENDSWITCH:
    case T_ENDWHILE:
```

**Comment by jails** [comment]
Glad you like it.
The main problem is Kahlan is relying on phpdbg/xdebug code coverage results which contain a lot of inconsistencies to build coverage reports.
I already added a couple of workaround Kahlan side to enhance coverage reports. Maybe identifying alternate control structures as "non coverable code" as @samsonasik suggested is the way to go. I'll need to think about it a bit.

**Comment by jails** [comment]
Should be fixed by https://github.com/kahlan/kahlan/commit/a3de05fe6a577bd1777df59d82eced98f783ee3e
@kilbiller feel free to test the dev branch (i.e. through "dev-dev" in your composer.json) so I can create a new release if fixed.

**Comment by samsonasik** [comment]
@jails I can verify that "kahlan/kahlan": "dev-dev" fixes the issue

**Comment by kilbiller** [comment]
@jails Well that was fast. It works for me too.

**Comment by jails** [comment]
Awesome, thanks for the head up guys :+1: , I'm closing this then.
