### ISSUE TITLE
Wrong total num of expectations

### ISSUE THREAD

**Issue by tyranron** [kahlan/kahlan#214]
Having [simple project with one expectation](https://github.com/kahlan/docker-image/tree/3fe0798577e3b0096069814a514f77fd5156de9c/test/app) I am receiving this on `3.1.4`:
```
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The PHP Test Framework for Freedom, Truth and Justice.

Working Directory: /app

.                                                                   1 / 1 (100%)



Expectations   : 1 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 3 of 3 PASS in 0.045 seconds (using 2Mo)
```

Expected behavior:
```
Passed 1 of 1 PASS in 0.045 seconds
```

**Comment by jails** [comment]
Good catch, it should have been fixed by https://github.com/kahlan/kahlan/commit/2fd5fc6fffb24b31d679618f8e391a5284a25846

I know there is still a couple of reporting inconsistencies in the 3.x branch but I think nobody will notice. The next 4.x major release should completely nail this down btw.

**Comment by tyranron** [comment]
Ok, NP.  
This was failing tests for Docker image. I tuned up test cases expectations temporary.
