### ISSUE TITLE
--coverage=4 should not show empty class as 100%

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#215]
For example, we have app structure:

```bash
 \                                             17 / 122      13.93%
├── App\                                        1 /  28       3.57%
│  ├── Controllers\                             1 /  19       5.26%
│  │  └── Home                                  1 /   1     100.00%
│  │     └── Home::index()                      1 /   1     100.00%
│  └── Models\                                  0 /   0     100.00%
│     └── Model                                 0 /   0     100.00%
```

The Model class itself is only a class with $table property:
```php
namespace App\Models;

class Model extends Model
{
	protected $table = 'user';
}
```
Also, I think the model itself should not be covered as I only test `Controllers\Home::index()`. 
I can write a Model class with syntax error, and the test still working because it actually never hit.

I created the reproducable repository for its use case at https://github.com/samsonasik/CodeIgniter4/tree/kahlan

```
$ git clone -b kahlan --single-branch git@github.com:samsonasik/CodeIgniter4.git
$ cd CodeIgniter4
$ composer install
$ vendor/bin/kahlan --coverage=4 --src=application/
```

**Comment by jails** [comment]
All classes of the `src` directory are loaded to give you an overview of what is missing to be covered. Indeed the coverage report must also show missing classes so you know you need to write some specs to them even if they weren't loaded during the test suite.

And if a class has no code I think the current behavior is correct. Indeed there's nothing to test on empty classes so your job is done for it. And if an error occurs during parsing, the report would crash and return a error afaik.

**Comment by samsonasik** [comment]
The probably an issue is if the model has an empty method:

```php
class TempModel extends Model
{
	protected $table = 'user';

	public function foo()
	{
		
	}
}
```
It still covered as 100% like the following:
```
│  └── Models\                                  0 /   0     100.00%
│     └── TempModel                             0 /   0     100.00%
│        └── TempModel::foo()                   0 /   0     100.00%
```

**Comment by samsonasik** [comment]
My idea is: How about if it is marked as 100% in terminal coverage summary, it will be shown also in html coverage ? Because current html coverage ( tried with istanbul ) is not showing empty class or class with empty functions like TempModel above.

**Comment by samsonasik** [comment]
Another issue related, if I have one empty method, and not empty method, For example:

```php
<?php namespace App\Models;

use CodeIgniter\Model;

class TempModel extends Model
{
	protected $table = 'user';

	public function foo()
	{
	}

	public function bar()
	{
		return 'bar';
	}
}
```

I got the following coverage:

Terminal:

![screen shot 2017-01-14 at 5 43 03 pm](https://cloud.githubusercontent.com/assets/459648/21954360/f9cf127c-da80-11e6-885d-2f6fe273a01e.png)


Html Coverage:

![screen shot 2017-01-14 at 5 43 15 pm](https://cloud.githubusercontent.com/assets/459648/21954363/fe6159d0-da80-11e6-9fc2-d6d615d5b546.png)

**Comment by jails** [comment]
If istanbul doesn't report empty class/functions, it's either a Kahlan issue which doesn't provide them in the json export or more likely an istanbul issue. Indeed empty classes/functions must be reported imo. Empty classes/functions may be dead code so reporting them is necessary so you know about them. Hiding them is non-sense imo.

And for your second example the HTML report seems consistent with the terminal report:
- TempModel is marked: 0% in both
- There's 0/1 line covered for both

And Statements/Branches/Functions are HTML report custom metrics.

**Comment by samsonasik** [comment]
Ok, closing it then. Thank you for the explanation.
