### ISSUE TITLE
Invalid Kahlan/Arg expectation

### ISSUE THREAD

**Issue by mbm-rafal** [kahlan/kahlan#216]
I'm using https://github.com/jarektkaczyk/laravel-kahlan extension for laravel 5.3

I have this expectation with argument declaration:

```
expect(app('events'))->toReceive('fire')->with(Arg::toBeA('array'));
```

I receive this error:

```
      ✖ it fires PersonDetachedFromPosition event after detached person
        expect->toReceive() failed in `./spec/unit/organisation/OrganisationSpec.php` line 105

        It expect actual to receive the expected method with expected parameters.

        actual received:
          (string) "fire"
        actual received times:
          (integer) 2
        actual received parameters list:
          (array) [
              0 => [
                  0 => an instance of `Illuminate\Database\Events\QueryExecuted`
              ],
              1 => [
                  0 => an instance of `Organisation\Events\PersonDetachedFromPosition`
              ]
          ]
        expected to receive:
          (string) "fire"
        expected parameters:
          (array) [
              0 => an instance of `Kahlan\Arg`
          ]

```

**Comment by jails** [comment]
According to the received parameters list present in the error message, the expectation should imo be:

```
expect(app('events'))->toReceive('fire')->with(
    Arg::toBeAnInstanceOf('Illuminate\Database\Events\QueryExecuted'),
    Arg::toBeAnInstanceOf('Organisation\Events\PersonDetachedFromPosition'),
);
```

**Comment by mbm-rafal** [comment]
It's not a case. It's about unexpected behavior of kahlan. It does not present appropriate infromation. 
The end case that I want to achive is 

```
expect(app('events'))->toReceive('fire')
                    ->with(Arg::toContain(
                        new Events\PersonDetachedFromPosition($person, $this->testPosition)
                    ));
```

which does not work as well because of same message that Kahlan/Arg is expected.

**Comment by jails** [comment]
Not sure to get what you mean. `Arg::toContain(...)` is creating a generic `Kahlan\Arg` instance which is used to perform some "generic" comparison. If the comparison doesn't match it means that the passed parameter doesn't pass your defined `Kahlan\Arg` instance.

Btw `new Events\PersonDetachedFromPosition($person, $this->testPosition)` creates a new instance so there's no way is can be present in a array somewhere. Use `Arg::toMatch()` with a closure instead like so:
```php
Arg::toMatch(function($arg) {
    // compare your arg
    // return a boolean to indicate whether the match passes or not;
});
```

**Comment by jails** [comment]
Ah you meant to output something like instead:
```
        ...
        expected parameters:
          (array) [
              0 => a `Kahlan\Arg` custom comparison ?
          ]

```

**Comment by mbm-rafal** [comment]
I want to check if method triggers event with particulary class (PersonDetachedFromPosition). 

You have right that I'm creating new instance and it could not be compared across kahlan/Arg. 
I think I have to use double or something here because I do not provide Event\PersonDetachedFromPosition object to event triggering method

**Comment by samsonasik** [comment]
As it actually received 2 times, I think you can do with `ordered` something like this:
```php
expect(app('events'))->toReceive('fire')
                     ->with(Arg::toBeAnInstanceOf('Illuminate\Database\Events\QueryExecuted'))
                     ->ordered;

expect(app('events'))->toReceive('fire')
                   ->with(Arg::toBeAnInstanceOf('Organisation\Events\PersonDetachedFromPosition'))
                   ->ordered;
```

**Comment by mbm-rafal** [comment]
@samsonasik  thank you, this works well.
