### ISSUE TITLE
Use function statement reported as non covered code

### ISSUE THREAD

**Issue by kilbiller** [kahlan/kahlan#219]
Hi,

I found another xdebug coverage related bug. When importing namespaced functions with the "use function" keywords the line is reported as non executed in the coverage report.

I guess using the same workaround as in #211 will solve the problem ?

**Comment by samsonasik** [comment]
@kilbiller it is covered. you probably missed register the files into composer.json `autoload`:

```json
    "autoload": {
        "files": [
            "src/Foo.php"
        ]
    },
```

I've created demo repository for it that shows that it works properly: https://github.com/samsonasik/kahlan-use-function

**Comment by jails** [comment]
Didn't see any issue with `use function`, however just fixed an issue with group use declarations (i.e with brackets) in the dev branch https://github.com/kahlan/kahlan/commit/6a1f30a0b3314329cab4b803e73700061026ea29

If it doesn't solve your issue please provide some example code so we can investigate.

**Comment by samsonasik** [comment]
@kilbiller please use `"kahlan/kahlan": "dev-dev"` for https://github.com/kahlan/kahlan/commit/6a1f30a0b3314329cab4b803e73700061026ea29 is the use case. Also, it is better to provide small, reproducable repository for your use case.

**Comment by kilbiller** [comment]
Yeah that was it, thank you.
