### ISSUE TITLE
Patch DateTime

### ISSUE THREAD

**Issue by urosgruber** [kahlan/kahlan#225]
I see that `allow('DateTime')->toBe(new DateTime('@123'));` works only with PHP > 7. How can this be used on 5.6. I checked docs but maybe I missed it. Thanks for help in advance.

**Comment by jails** [comment]
The substitution feature for PHP<7 has been removed in kahlan 3.1.0. The first attempt to make this feature to work for all PHP versions generates some syntax errors in some certain circumstances. The issue has been solved by relying on the uniform variable syntax which is only supported by PHP>=7. So there's no way to make it work in PHP<7.

If it's a legacy project try the kahlan 3.0.3 version (and remove the `/tmp/kahlan` directory after that). Maybe your code base won't hit the syntax error issue, but imo upgrading to PHP>=7 is the safer way.

**Comment by urosgruber** [comment]
Ok, Btw I tried downgrade even before I posted this question and for some reason even on 3.0.3 give me the same error where I see that date was not mocked at all. I can't find any `/tmp/kahlan`

**Comment by samsonasik** [comment]
@urosgruber may be patchwork can be a solution ? http://patchwork2.org/examples/

**Comment by jails** [comment]
@urosgruber if you didn't cleared the cache files it won't work. do a `echo sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'kahlan';` in a php file to get the cache dir path in your system.

**Comment by urosgruber** [comment]
@jails thanks for the tip. I forgot about this function even exists.
