### ISSUE TITLE
Autocompletion in IDE (phpstorm)

### ISSUE THREAD

**Issue by stevep** [kahlan/kahlan#227]
I love using this library to write tests, they're so natural and clean looking. One major issue I have is because of the use of magic `__get` on the `Scope` to access variables defined on `$this`, phpstorm has no idea what the type of the variable is, and offers no autocomplete when trying to test my code.

Here is an example:

```php
beforeEach(function () {
    $this->subject = new PostTypeBuilder('subject');
});

it('has a post type name', function () {
    $postTypeName = $this->subject->getPostTypeName();
    expect($postTypeName)->toBe('subject');
});
```
phpstorm has no idea that `$this->subject` is an instance of `PostTypeBuilder` therefore it can offer no autocompletion while typing.

My question is, in anyone's experience, is there a way around this? Is there a way to can tell the IDE what the type of the variable is?

@tyranron talks about this a bit in issue: #53 and was passing the variable into each closure with `use`  but for a number of reasons I imagine this is bad, mostly because it won't get reinitialized each test.

**Comment by tyranron** [comment]
@stevep if you pass variables by reference in `use()` block it works as expected.

However, there is no "silver bullet" to solve this issue =/

I'm using 3 ways to overcome this (depending on what suites best in concrete case):
1. As you referred above: pass the reference inside `use()` statement. The downside of this way is that specs loose it's readability.
2. Explicitly specify type in phpDoc comment (like `/** @var PostTypeBuilder $someVar */`). Bad for nested types as requires to acquire their name.
3. Try to avoid using `$this` for complex types as much as possible. If constructor is simple - just create object directly inside `it()` case.

**Comment by stevep** [comment]
@tyranron Thank you for the very detailed reply. All three have their tradeoffs it seems. The best solution would be for phpstorm to integrate it for us, but I don't see that happening.

**Comment by stevep** [comment]
Another option which builds upon your 3rd option, is to create a separate initialize function. Might be extra handy if its more complicated than just initializing one variable.

```php
function getSubject(): PostTypeBuilder {
    return new PostTypeBuilder('subject');
}

it('has a post type name', function () {
    $subject = getSubject();
    $postTypeName = $subject->getPostTypeName();
    expect($postTypeName)->toBe('subject');
});
```

**Comment by jails** [comment]
Thanks @stevep and @tyranron for the head up on this subject. Unfortunately looks like there's nothing we can do Kahlan's side. I hope your advices will help other PHPStorm users in their autocompletion quest anyway.
