### ISSUE TITLE
Kahlan is conflicting with codeception because of "expect" function

### ISSUE THREAD

**Issue by mieszkomalawski** [kahlan/kahlan#228]
Codeception defines "expect" which Kahlan tries to redefine. This results in:

"Kahlan's global functions are missing because of some naming collisions with another library."

As a result You can't have both in one project

This may be potentially bigger issue as many other packages can interfere with kahlan

**Comment by jails** [comment]
Kahlan should be able to work in insulation.

If you add this constant before loading the composer autoloader:
```php
defined('KAHLAN_DISABLE_FUNCTIONS', true);
```
Or setting `'KAHLAN_DISABLE_FUNCTIONS'` as an environment variable, so that `getenv('KAHLAN_DISABLE_FUNCTIONS')` returns `true`, Kahlan's global functions won't be loaded.

Then you will be able to import namespaced functions like:
```php
use function kahlan\describe`;
use function kahlan\it`;
use function kahlan\expect`;
// etc.
```
However I've no idea if it's possible to do it the same with Codeception so both frameworks won't collide.

**Comment by jails** [comment]
Btw maybe @ddziaduch can share his experience on this issue by exposing how he did manage his PHPSpec/Behat/Kahlan conflict related to the global API.

**Comment by mieszkomalawski** [comment]
After adding `defined('KAHLAN_DISABLE_FUNCTIONS', true);`

And importing 

`use function kahlan\describe`;
use function kahlan\it`;
use function kahlan\expect`;`

To my spec

Running vendor/bin/kahlan results in following:

 Uncaught exception 'Kahlan\Box\BoxException' with message 'Unexisting box `'kahlan'`.' in vendor/kahlan/kahlan/src/functions.php:131

After some debugging I noticed that when I use kahlan functions in global namespace, before describe function call "kahlan" box is registered with "box" function.

However when I add `use function kahlan\describe`;` even without declaring `defined('KAHLAN_DISABLE_FUNCTIONS', true);` then "kahlan" box does NOT get registered before describe function call resulting in exception mentioned above

**Comment by jails** [comment]
Just pushed a fix in the [dev](https://github.com/kahlan/kahlan/commit/a2c291c6be6dc154cbb1a09fd2ab9b616e6a873d) branch, does it solve the issue ?

**Comment by mieszkomalawski** [comment]
It Works! Thanks a lot!

On a side note, it would be great if `Kahlan's global functions are missing because of some naming collisions with another library. ` error message could scecify which function exactly are causing collisions. I can submit merge request in spare time, probably  tomorrow.

Also: it would be great to add this solution to documentation. It's also worth to mention that if You are using configuration file eg. kahlan-config.php You must place `define('KAHLAN_DISABLE_FUNCTIONS', true);` in config not in specs.

**Comment by jails** [comment]
Good catch, [just refactored](https://github.com/kahlan/kahlan/commit/c7d56b35c224c6c52509ebdf56deb97b573744fd) how global functions are loaded so now error messages should indicate which global function actually collide.

**Comment by jails** [comment]
Tagged in 3.1.10.
