### ISSUE TITLE
die statement not converted to QuitException

### ISSUE THREAD

**Issue by mieszkomalawski** [kahlan/kahlan#229]
When using use Kahlan\Plugin\Quit;

die() is converted to QuitException 
but die is not 

Following code will not throw QuitException:

function foo(){
   die;
}

It will just die

No exception is thrown despite calling Quit::disable(); in spec

**Comment by samsonasik** [comment]
could you try `die()` with parenthesis instead of `die` ?

**Comment by mieszkomalawski** [comment]
Hi

I know that `die()` will work, but `die` will not. At least it could be mentioned in docs.

I had to test legacy code that had `die` statements in it. I could not understand why it's not getting converted to QuitException. After 1h+ of debugging I figured out that changing `die` to `die()` will work

**Comment by jails** [comment]
Thanks for reporting, I've fixed it in the [dev branch](https://github.com/kahlan/kahlan/commit/636bd064f35f1e22749973b58c6d2524d1d104ed). Feel free to test so I can merge it to the master branch and tag a new release.

**Comment by samsonasik** [comment]
@jails I can verify that https://github.com/kahlan/kahlan/commit/636bd064f35f1e22749973b58c6d2524d1d104ed fixed it, tried at https://github.com/sitrunlab/learn-kahlan/commit/7fec6fdfe3e8790b2944297b218b057cbddde1de with green travis build : https://travis-ci.org/sitrunlab/learn-kahlan/builds/212592269

@mieszkomalawski please test with set `"kahlan/kahlan": "dev-dev"` in your composer.json and composer update.

**Comment by jails** [comment]
Well done @samsonasik :+1: 
The fix has been landed in 3.1.9
