### ISSUE TITLE
Documentation for expect calls on the matchers page invalid?

### ISSUE THREAD

**Issue by gwigz** [kahlan/kahlan#236]
```php
expect('time')->toBeCalled()->andReturn(strtotime("now"));
```
```
PHP Fatal error:  Call to undefined method Kahlan\Matcher\ToBeCalled::andReturn()
```

**Comment by jails** [comment]
I didn't find where the documentation is incorrect. Can you please point where it should be updated or better opening a PR ?

Indeed `expect()->toBeCalled()` and `allow('time')->toBeCalled()` has two different meaning.

`expect()` verifies that something has been actually been called while `allow()` stubs methods/functions.

A valid example could be:
```php
allow('time')->toBeCalled()->andReturn(strtotime("now"));
// running the logic here
expect()->toBeCalled();
```

**Comment by samsonasik** [comment]
@gwigz you may refer unpublished documentation, see this commit at docs https://github.com/kahlan/docs/commit/7796426fa59a8f453224e337545a694910fd1f7b

**Comment by gwigz** [comment]
I thought so, I got that snippet from https://kahlan.github.io/docs/matchers.html (the "function invocation matchers" section).

**Comment by jails** [comment]
Ah right, the last documentation hasn't been deployed on `gh-pages`
