### ISSUE TITLE
Error reporting - Expect()->toReceive suppressing undefined errors

### ISSUE THREAD

**Issue by Ashfitzg** [kahlan/kahlan#237]
If I perform the following test:

```php
describe('borked', function () {
    it ('supresses error after toReceive is registerd', function () {
        $foo = new Foo;
        expect($foo)->toReceive('bar');
        expect($foo->bar())->toBe('test');
        expect($foo->thisisnotdefined)->toBe('test');
    })
})
```
Instead of it raising an exception and failing the test when referencing an undefined variable, the test result will be recorded as 'pending'. The correct behaviour would be raising the exception.

**Comment by samsonasik** [comment]
No, I think use E_NOTICE already correct. make it pending will make a wrong code exists in your app.

**Comment by Ashfitzg** [comment]
Ha, little bit of a miscommunication, raising a notice and failing the test would be the expected behaviour. The current behaviour is to suppress the error and record the test as pending.

**Comment by gwigz** [comment]
_Didn't mean to press that._

I'm experiencing this too.

**Comment by jails** [comment]
Correct, thanks for the report.
It should have been fixed in the [dev branch](https://github.com/kahlan/kahlan/commit/c7ac13eb48cab72daf99cdf5e6bc9be2a57d372a).
