### ISSUE TITLE
Integration with Phony

### ISSUE THREAD

**Issue by ezzatron** [kahlan/kahlan#240]
Hi there, I'm a maintainer for [Peridot](http://peridot-php.github.io/), and the author of the mocking framework [Phony](http://eloquent-software.com/phony/latest/), and I'm interested in how I would go about writing an integration for using Phony within Kahlan.

In particular, there are three things I'm wondering about:

1. Is there any way to extend the `expect()` interface?
2. Does Kahlan distinguish between "failures" and "errors" (like PHPUnit), or does it treat all exceptions in tests in the same way?
3. Is there any way to auto-inject arguments to `describe()` and `it()` blocks, so that something similar to [peridot-phony's Injected mock objects](https://github.com/eloquent/peridot-phony#injected-mock-objects) could be implemented?

You might also be wondering why there's value in Phony integration, when Kahlan has its own test doubles and stubs. There's [lots of reasons](https://github.com/eloquent/phony#why-use-phony), but chief among them is that Phony actually provides a different mocking "style" to Kahlan's built-in system.

Kahlan's built-in stubs seem to implement what's commonly referred to as the [expect-run-verify](https://monkeyisland.pl/2008/02/01/deathwish/) pattern, which mocking frameworks like [Phake](http://phake.readthedocs.io/) and Phony have deliberately avoided. People who are used to the benefits of Phake and Phony will likely find the use of expect-run-verify style mocks to be a big drawback to using Kahlan.

In any case, great work on Kahlan, it's nice to see PHP people who get how good `describe()`/`it()` can be 😄

**Comment by jails** [comment]
Definitely, would love to help here. Right now I'm working on a 4.0 so it may the right spot to make necessary changes to make it works.

1. Right now expectation are created [here](https://github.com/kahlan/kahlan/blob/4.0/src/Block/Specification.php#L50). For customs "behavior" Kahlan use a filter system (instead of an event based system). For example, [this piece of code](https://github.com/kahlan/kahlan/blob/4.0/src/Cli/Kahlan.php#L634-L636) make the `stop()` method filterable so people can do what they want when specs finished their execution. At this point I planned to change the filtering API to use [this one](https://github.com/crysalead/filter). The API is a bit less verbose. Anyway we can use the Kahlan's current syntax for now since it has the same capabilities.

2. In Kahlan a failure occurs when an expectation failed, while an error/exception identify a spec which throws an uncatched exception, so failures and error/exception have a different meaning. And during the reporting failures and errors/exceptions are reported differently. So I guess the answer is yes.

3. Maybe we can also add some filters (with probably some refactoring to make the filter easy to use) where `describe()` and `it()` are runned i.e there https://github.com/kahlan/kahlan/blob/4.0/src/Block/Specification.php#L74-L89 and there https://github.com/kahlan/kahlan/blob/4.0/src/Block/Group.php#L162-L170

Just created a [4.0-phony branch](https://github.com/kahlan/kahlan/tree/4.0-phony) so feel free give it a go and ask me questions if you need more informations on the internal.

**Comment by ezzatron** [comment]
Thanks for the awesome response. I've got a bit of work to do on Phony coming up, so hopefully I can explore this stuff in more depth soon.

With the filter system, do you know if it's possible to add methods to your `Expectation` class? For example, can I use filters to add `Expectation::toHaveBeenCalledWith()`, or would I have to filter `expect()` to return my own expectation class that implements new methods instead?

**Comment by jails** [comment]
Oh you don't need to use the filtering system for that. The default `Expectation` class support custom matchers.

To add a new matcher you will need to create a static class like the following:
```php
namespace My\Namespace;

class ToHaveBeenCalledWith
{
    public static function match($actual, $expected = null)
    {
        // return true/false;
    }

    public static function description()
    {
        return "have been called with expected.";
    }
}
```
Once created you only need to register it using the following syntax:
```php
Kahlan\Matcher::register('toHaveBeenCalledWith', 'My\Namespace\ToHaveBeenCalledWith');
```

It's also possible to register a matcher to work only for a specific class name to keep the API consistent.

Example:
```php
Kahlan\Matcher::register('toHaveBeenCalledWith', My\Namespace\ToHaveBeenCalledWith', ' Some\Phony\Mock');
```

There's already an existing repo with some [custom matchers here](https://github.com/kahlan/extra-matcher) if you want to seen how it works in practice.

**Comment by ezzatron** [comment]
Hey, I've made some progress on this over at [ezzatron/phony-kahlan](https://github.com/ezzatron/phony-kahlan). I can now run a spec that looks like this:

```php
<?php

use function Eloquent\Phony\Kahlan\mock;

describe('Phony', function () {
    beforeEach(function () {
        $this->handle = mock('Eloquent\Phony\Kahlan\Test\TestClassA');
        $this->mock = $this->handle->get();
    });

    it('should record passing mock assertions', function () {
        $this->mock->testClassAMethodA('aardvark', 'bonobo');

        $this->handle->testClassAMethodA->calledWith('aardvark', 'bonobo');
    });

    it('should record failing mock assertions', function () {
        $this->mock->testClassAMethodA('aardvark', ['bonobo', 'capybara', 'dugong']);
        $this->mock->testClassAMethodA('armadillo', ['bonobo', 'chameleon', 'dormouse']);

        $this->handle->testClassAMethodA->calledWith('aardvark', ['bonobo', 'chameleon', 'dugong']);
    });
});
```

And get a result that looks like this:

<img width="851" alt="screen shot 2017-06-22 at 10 41 15 pm" src="https://user-images.githubusercontent.com/100152/27434428-0654271a-579c-11e7-806b-e59e794ec5e1.png">

As you can see, it still needs a fair bit of work, but it's progress. I'll update this issue with some ideas for better integration soon, but for now it's bedtime 😴

**Comment by ezzatron** [comment]
Oh, and if you want to try it for yourself, it should be as simple as cloning the repo and running `make integration`.

**Comment by jails** [comment]
Awesome, that's really neat !!
Sure, happy to help if you encounter some integration difficulties with Kahlan but looks like you already nailed it down on your own :smiley: !

**Comment by ezzatron** [comment]
Sorry for the wall of text below, I just wanted to get into a bit of detail about the problems I encountered. Hopefully most of it makes sense. It would be really helpful to get your opinion on some of these problems before I continue working on this integration.

It's definitely cool that this already *sort of* works, but some of the things I had to do were pretty "hacky", and the console output has some problems. To get *really* good integration between Phony and Kahlan might require some changes in Kahlan itself, so I'll try to get a fork of Kahlan going to demonstrate the kind of things I'm talking about as well.

**Recording assertions**

The most important integration point Phony needs is a way to tell the test framework that an assertion was made. At the moment, for Kahlan, I'm using two different strategies for passing and failing assertions.

For passing assertions I simply `expect(null)->toBe(null)`, which works well enough, but would probably look strange if Kahlan ever reports on what types of assertions have been made.

For failing assertions, I'm using `Matcher::register()` to register a matcher called `phonyFailure`, that *always* fails, which I can then use to pass Phony's failure description to Kahlan by using `expect(null)->phonyFailure($description)`. There are a few problems with this approach:

- Kahlan reports that `expect->phonyFailure()` was called, but the person writing the spec never calls this, it's only used internally by `phony-kahlan`.
- Kahlan starts the failure text with "It expect actual to ", followed by the Phony error description, which doesn't read very nicely. Phony has its own description of the expectation, so you end up with something like "It expect actual to Expected ClassName[1]->methodName call with arguments: ...".
- Kahlan displays the "actual" value, but this is always `null`.
- Kahlan repeats the description again at the bottom. Phony's descriptions can get very large, especially when there are a lot of function calls.

For both of these cases (passing and failing assertions), it would be much nicer to be able to bypass the `expect()` interface completely, and have access to something like `pass()` and `fail($description)`. If I could call `fail()` with a description, and bypass a lot of the display formatting that Kahlan normally does for failures, the console output would look much nicer. This would probably still need to handle indentation.

Since `pass()`/`fail()` *probably* shouldn't be used directly by spec writers, I think they belong on the `Suite` interface, rather than adding more global functions. So they could be used like `Suite::current()->fail($description)`.

**Argument matcher support**

Phony can support third-party argument matchers like Kahlan's `Arg::toBeX()` system. I managed to get this working, but there are some times when it is necessary to "describe" the matcher as a string. For example, for the following assertion:

```php
it('should have been called with a DateTime', function () {
    $spy = spy();
    $spy->calledWith(Kahlan\Arg::toBeAnInstanceOf(DateTime::class));
});
```

Produces an error description like this:

```
Expected spy#0[0] call with arguments:
    ✗ <toBeAnInstanceOf ("DateTime")> (0 matches)
Never called.
```

In order to do this, I currently have to use reflection, because all of the properties of `Kahlan\Arg` are `private`. And the only useful information I have is `_name` and `_args`, which means the description is not as nice to read as it could be. Relying on `private` properties is obviously not ideal, because if the internals of Kahlan change, my implementation could break.

Matcher systems like [Hamcrest matchers](https://github.com/hamcrest/hamcrest-php) and [PHPUnit's "constraints"](https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertThat.tables.constraints) implement their own description systems, and support `__toString()` for argument matchers.

If Kahlan implemented this kind of argument matcher description system, then Phony could produce better failure messages, that might look more like this:

```
Expected spy#0[0] call with arguments:
    ✗ <an instanceof DateTime> (0 matches)
Never called.
```

**Extending the `expect()` interface**

I haven't attempted to implement new `expect()` matchers yet. This is a pretty big task because Phony has [a lot of assertions](http://eloquent-software.com/phony/latest/#api) to implement. It may even turn out that it's not worth the effort. But there are a couple of things that I know will be tricky if I try to do this.

Phony has a system like Kahlan's `expect()->not` attribute, but there are more options, and some of them have parameters, including:

- [`->never()`](http://eloquent-software.com/phony/latest/#spy.never) (equivalent to `->not`)
- [`->once()`](http://eloquent-software.com/phony/latest/#spy.once)
- [`->twice()`](http://eloquent-software.com/phony/latest/#spy.twice)
- [`->thrice()`](http://eloquent-software.com/phony/latest/#spy.thrice)
- [`->times($times)`](http://eloquent-software.com/phony/latest/#spy.times)
- [`->atLeast($times)`](http://eloquent-software.com/phony/latest/#spy.atLeast)
- [`->atMost($times)`](http://eloquent-software.com/phony/latest/#spy.atMost)
- [`->between($minimum, $maximum)`](http://eloquent-software.com/phony/latest/#spy.between)
- [`->always()`](http://eloquent-software.com/phony/latest/#spy.always)

I am not sure how to go about implementing these using Kahlan's expectations. Do you think it might be possible, and do you have any advice for how to implement this?

Another problem is how to implement Phony's [order verification](http://eloquent-software.com/phony/latest/#order-verification) system. In Phony, you can make assertions about the order of operations, using the result of a previous assertion, like so:

```php
inOrder(
    $spyA->calledWith('a'),
    $spyA->returned('x'),
    $spyB->calledWith('b'),
    $spyB->returned('y')
);
```

Ideally, you would be able to do something similar with the `expect()` interface, like this:

```php
expect(
    expect($spyA)->toHaveBeenCalledWith('a'),
    expect($spyA)->toHaveReturned('x'),
    expect($spyB)->toHaveBeenCalledWith('b'),
    expect($spyB)->toHaveReturned('y')
)->toHappenInOrder();
```

But you can see that there are a couple of difficult things here.

First, there are multiple "actual" values in a list instead of just one. This could be done with an array instead, but it's not as "nice". Perhaps support could be added for this syntax? It might be useful for other integrations too.

Second, the outer expectation needs to be able to access the results of the inner expectations to actually check the order. I think that this should be possible to implement with Kahlan's "deferred" matchers.

**Automatic mock injection**

We already talked about this feature a little, but I haven't had a chance to try the filter system and see if I can get it working yet. I'm still interested in giving it a go. For an example of another popular test framework that does this, see the way that [phpspec supports typehints for test doubles](http://www.phpspec.net/en/stable/manual/prophet-objects.html#spies).

**Comment by jails** [comment]
Wooow just saw you added a couple of PR so let's close this and start talking on the different PR instead !

**Comment by ezzatron** [comment]
@jails I just released a [version 0.1.0](https://github.com/eloquent/phony-kahlan/releases/0.1.0) of [phony-kahlan](https://github.com/eloquent/phony-kahlan), running off the current `4.0-phony` branch of Kahlan.

As for the other integration points:
- If you decide to implement something like #261, then I will re-introduce the auto-injection feature. I still have the code in a branch ready to go.
- I had a go at adding my own `expect($spy)->toHaveBeenCalled()` etc. but to really be a good integration, it would require further changes to Kahlan's expectations/matchers, and a lot of new classes and methods on my end. Considering the scope of the work, I don't think it's really worth it at the moment. It would be nice to tackle in the future perhaps.

So... how far away is 4.0.0? 😁😁😁

**Comment by ezzatron** [comment]
@jails I shipped Phony `2.0.0` today, which means that installation instructions for `phony-kahlan` finally made it in to the main docs! Check it out [here](http://eloquent-software.com/phony/latest/#kahlan-usage) and [here](http://eloquent-software.com/phony/latest/#installation).

You'll have to let me know when Kahlan 4.0 ships, and maybe we can make some coordinated posts on Reddit etc. announcing the new Kahlan/Phony integration. What do you think?

**Comment by jails** [comment]
Awesome :+1: 
Sorry for the delay, just pushed some last changes before tagging the official 4.0 release.
I first wanted to add a couple of new features but I think it can wait for the next release :-p.
So yeah that's definitely a good idea, I'm ready for some coordinated posts :100:

**Comment by ezzatron** [comment]
If you have the time to spare, I wrote up an article on using Kahlan and Phony together - [Phony and Kahlan by example](http://eloquent-software.com/phony/master/kahlan-by-example). I thought it would be useful to have something to link people to on release day.

You might also be able to teach me some relevant Kahlan tricks that I don't know about, which I could incorporate into the article.

**Comment by jails** [comment]
That's a really great article and use case :+1: 
The only comment I can make is you can now replace the 4.0.x-dev reference by the 4.0.0 one ^^

**Comment by ezzatron** [comment]
Thanks! And congratulations on `4.0.0`! I'll make a `1.0.0` version of phony-kahlan and update the article ASAP.

**Comment by ezzatron** [comment]
I released a stable version of `phony-kahlan`, and updated the article with both.

Hopefully I can find some time tonight to write up the post announcing the new versions of Phony and Phony for Kahlan. If you send me an email at ezzatron@gmail.com, I can send you through a copy of what I am planning to post, so that we can coordinate.
