### ISSUE TITLE
Function stubbing does not work and kahlan own specs fail

### ISSUE THREAD

**Issue by Isinlor** [kahlan/kahlan#244]
Hello,

I have an issue with stubbing `random_int` (and apparently any other function):

```php
<?php

describe('random_int', function() {

    it('returns 2', function () {

        allow('random_int')->toBeCalled()->andReturn(2);
        expect('random_int')->toBeCalled();

        expect(random_int(0, 1))->toBe(2);

    });

});
```

It fails like so:
```
random_int
  ✖ it returns 2
    expect->toBeCalled() failed in `./spec/RandomIntSpec.php` line 17
    
    It expect actual to be called.
    
    actual:
      (string) "random_int()"
    actual called times:
      (integer) 0
    expected to be called:
      (string) "random_int()"
    
    expect->toBe() failed in `./spec/RandomIntSpec.php` line 19
    
    It expect actual to be identical to expected (===).
    
    actual:
      (integer) 1
    expected:
      (integer) 2
    
```

I tried to investigate what is the cause of this issue. Therefore I went to my vendor directory, installed  composer dependencies of kahlan and run the kahlan own specifications. The result is that 12 tests failed and one throws an exception - all related to the `Interceptor`.

Then I cloned the orginal kahlan repository and repeted the procedure. It works as expected.

I was curious if the issue is caused by configuration of my project, therefore I created a new one and tested again. It fails as well. The repository is avliable here: https://github.com/Isinlor/kahlan-issue

Steps to reproduce:
```
git clone https://github.com/Isinlor/kahlan-issue.git
cd ./kahlan-issue/
composer install
vendor/bin/kahlan # function stubbing test
cd ./vendor/kahlan/kahlan/
composer install
bin/kahlan # kahlan own tests
```

My PHP version:
```
PHP 7.0.2 (cli) (built: Jan  8 2016 10:14:20) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans
```

Composer version:
```
Composer 1.3.2 2017-01-27 18:23:41
```

Thanks for help!

**Comment by jails** [comment]
Hi,
One of PHP's assumptions is that once you define a function/class it stays defined forever. So the only way for Kahlan to stub/monkey path functions/classes is to perform some "Just In Time" code rewriting during Composer's autoloading.

So if you try to stub or monkey patch something inside a spec file it won't get intercepted by JIT patchers and so won't be patched. So all the code present in *.spec.php files are not intercepted and therefore not patchable.

The only way to patch something is to use them in classes and make them loaded by Composer by adding a `use MyApp\MyClass;` in top of your spec file. That way you will be able to patch your core function.

**Comment by Isinlor** [comment]
Hmm... I have started from `random_int` called in my class, but it did not work. Only then I attempted to simplify the test case (apparently I have oversimplified). But I tested it again and now it seems to work. I think I got confused. I had JIT disabled in my config and I'm sure I have re-enabled it, but maybe only after I have oversimplified the test case.

Anyway, big thanks for such a quick response! You are the best :1st_place_medal: 

Just out of curiosity. Do you have an idea why kahlan own test suite  fails when run from a vendor?

**Comment by jails** [comment]
You bet !
When kahlan is executed through the vendor directory it loads the Composer autoloader of the Kahlan's vendor file as well as the Composer autoloader of the main project file.
So there's two composer autoloaders loaded. However the fact that Kahlan is tested using the Kahlan test framework itself it requires some tricks (e.g to disable JIT patching) which doesn't work in this running configuration.
