### ISSUE TITLE
FerVer Deprecated

### ISSUE THREAD

**Issue by jhabdas** [kahlan/kahlan#245]
Please adjust accordingly and use SemVer 2.0 spec. Thanks!

https://github.com/jonathanong/ferver

**Comment by jails** [comment]
Wise enough, feel free to open a PR on the dev branch :+1:

**Comment by jails** [comment]
Fixed in https://github.com/kahlan/kahlan/pull/247/commits/5f3643de054efaa9b162c66b5300b0ea346a9ada
