### ISSUE TITLE
Cannot Quit procedural code

### ISSUE THREAD

**Issue by jhabdas** [kahlan/kahlan#249]
Given the following source file:

```php
namespace hyperdrive;
defined( 'ABSPATH' ) || die( 'Now you are going to die! BAM!' );
function enter_hyperspace( $dark_energy ) {
  echo "<script>{$dark_energy}</script>";
}
```

And given the following spec:

```php
namespace hyperdrive\spec;

use Kahlan\QuitException;
use Kahlan\Plugin\Quit;

use function hyperdrive\enter_hyperspace;

describe('hyperdrive', function () {
  describe('enter_hyperspace()', function () {
    it('echos empty script given empty string', function () {
      Quit::disable();
      $closure = function() { enter_hyperspace(''); };
      expect($closure)->toEcho('<script></script>');
    });
  });
});
```

I receive the following output upon executing the test runner:

<samp>Now you are going to die! BAM!%</samp>

Whereas I would not expect the program to exit, but instead throw an exception and squelch it.

**Comment by jhabdas** [comment]
With a resolution to this issue the following statement in [the docs](https://kahlan.github.io/docs/quit.html) will need to be updated:

> **Note:** monkey patching only works for **classes loaded by Composer**.

**Comment by jails** [comment]
The only way to patch something is to have it loaded through Composer through a `use` statement. Directly requiring files doesn't go through the autoloader class so the "Just In Time" rewriting is not applied.

The only way to make it works is to load the file **before** it's loaded in the application by adding somethink like this in your `kahlan-config.php` (didn't ever tested but it should work):

```php
use Kahlan\Filter\Filter

Filter::register('autoload', function($chain) {
    $this->autoloader()->loadFile('some/file/path/to/load.php');
});

Filter::apply($this, 'namespaces', 'autoload');
```
This in your files you will need to add some conditions like:

```php
if (!function_exists('myFunction')) {
    //...
}
```
or simply using for the whole file:
```php
if (!defined('KAHLAN_VERSION') {
    //...
}
```
So the file won't be included twice.
It should work.

**Comment by jhabdas** [comment]
> The only way to patch something is to have it loaded through Composer through a use statement.

Check.

> The only way to make it works is to [...]

I'm on it.

**Comment by jhabdas** [comment]
For reference, here's my current composer set-up which allows the namespacing to work in conjunction with Kalan without issue thanks to a [well placed tip](https://github.com/sitrunlab/learn-kahlan/issues/7#issuecomment-302328260) from @samsonasik:

```php
"autoload": {
  "files": [
    "src/hyperdrive.php"
  ]
}
```

**Comment by jhabdas** [comment]
> Directly requiring files doesn't go through the autoloader class so the "Just In Time" rewriting is not applied.

This statement gives me pause in that I'm already using the autoloader and not directly requiring files. I've linked my test implementation via GitHub above if you'd like to take a peek at my setup. Meanwhile I'll look at cajoling the config file to do my bidding.

**Comment by jails** [comment]
You're right `"autoload": {"files"}` [is not supported by kahlan](https://github.com/kahlan/kahlan/issues/232)

Indeed, `"files"` entries are loaded by composer but way before Kahlan itself. So when `require 'vendor/autoload.php'` is done, all `"files"` entries has already been required and there's no way to patch them anymore.

In the next Kahlan version I'll probably embed in Kahlan a custom version 'vendor/autoload.php' file so even files in `"files"` will be patched. But at this time it's highly experimental.

**Comment by jails** [comment]
An actual workaround is to put your function's logic inside some static method instead like:
```php
namespace hyperdrive;
use hyperdrive\Hyperdrive;

function enter_hyperspace() {
    Hyperdrive::enter_hyperspace();
}
```
This way `Hyperdrive` will be lazily autoloaded by composer when `enter_hyperspace()` will actually be called and it should work.

**Comment by jhabdas** [comment]
Thanks @jails. Lots of angles to pursue, and that workaround is super clever. I'm happy to go as experimental as you like, if you like. My main goal is clean and testable code, zero `extends` and no `class` to ensure OOP doesn't get introduced into my codebase.

**Comment by jails** [comment]
Looking forward your final implementation ;-)

**Comment by jhabdas** [comment]
> You're right `"autoload": {"files"}` is not supported by kahlan

Just to be sure we're on the same page I'm having no trouble using kahlan with file autoloading, and not using `require` statements.

<img width="762" alt="screen shot 2017-05-21 at 7 53 36 pm" src="https://cloud.githubusercontent.com/assets/440298/26283682/39304db8-3e5f-11e7-836b-06cb0172923e.png">

It's the Quit statement I can't get working. Sorry if that wasn't clear in the OP.

**Comment by jhabdas** [comment]
I'll make a point to continue hanging out in the IRC # while I'm implementing.

**Comment by jails** [comment]
By " `"autoload": {"files"}` is not supported by kahlan" I meant that you will get your files autoloaded correctly however monkey patching won't work so `Quit::disable();` which requires files to be patched to work.

**Comment by LostKobrakai** [comment]
Just to add a bit reasoning to it: file autoloading in composer does use plain php include statements, so kahlan doesn't have a point of intercepting the loaded code and replacing it with it's own patched version. All other composer autoloading stategies do not include files directly, but do so on demand. That's the place where kahlan does it's magic for monkey patching.

**Comment by jhabdas** [comment]
Thanks for additional info. Still learning about packages in PHP. The whole autoloading thing is still a bit of a black box to me, but I'm getting there. After a chat with @jails on IRC I'm planning to explore use of the patchwork lib for getting the job done. Other than two magic methods and one side affect already handled by kalan, I have pure functions so I expect to make minced meat of things just as soon as I get over this hurdle. Cheers.

**Comment by jhabdas** [comment]
https://github.com/antecedent/patchwork/issues/59
