### ISSUE TITLE
Function name must be a string

### ISSUE THREAD

**Issue by jhabdas** [kahlan/kahlan#251]
For those testing procedural code without use of classes you may encounter the named error in cases where you're trying to do something like this:

```php
it('echos string given as argument', function () {
  expect(myFunction('foo'))->toEcho('foo');
});
```

If that's the case you may find value in wrapping your function call inside a closure, as shown here:

```php
it('echos string given as argument', function () {
  $closure = function () { myFunction(''); };
  expect($closure)->toEcho('foo');
});
```

**Comment by LostKobrakai** [comment]
The reasoning here is that in the first example `echoInput()` is executed, when then test is parsed and `expect()` is only given the return value, whereas in the second one `expect()` is given a executable closure, which can be later executed, when the actual testing does happen.
