### ISSUE TITLE
toBeAnInstanceOf reports the kahlan source line number rather than the specs

### ISSUE THREAD

**Issue by deployable** [kahlan/kahlan#252]
When testing a value with `toBeAnInstanceOf()` kahlan reports it's own source line number in `Expectation.php` rather than the line in the spec that is running the test. 

Spec
```
<?php
class Whatever{}
class NotWhatever{}

describe('toBeAnInstanceOf()', function(){

  it('should be a Whatever', function(){
    expect( (new Whatever()) )->toBeAnInstanceOf('Whatever');
  });

  it('should report the test source line number for false', function(){
    expect( false )->toBeAnInstanceOf('Whatever');
  });

  it('should report the test source line number for NotWhatever', function(){
    expect( (new NotWhatever()) )->toBeAnInstanceOf('Whatever');
  });

});
```
Run
```
→./vendor/kahlan/kahlan/bin/kahlan --no-header --pattern=spec/TestSpec.php 

.FF                                                                 3 / 3 (100%)

toBeAnInstanceOf()
  ✖ it should report the test source line number for false
    expect->toBeAnInstanceOf() failed in `./vendor/kahlan/kahlan/src/Expectation.php` line 332
    
    It expect actual to be an instance of expected.
    
    actual:
      (boolean) false
    expected:
      (string) "Whatever"
    
toBeAnInstanceOf()
  ✖ it should report the test source line number for NotWhatever
    expect->toBeAnInstanceOf() failed in `./vendor/kahlan/kahlan/src/Expectation.php` line 332
    
    It expect actual to be an instance of expected.
    
    actual:
      (object) an instance of `NotWhatever`
    expected:
      (string) "Whatever"
    


Expectations   : 3 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 1 of 3 FAIL (FAILURE: 2) in 0.016 seconds (using 2Mo)
```

**Comment by samsonasik** [comment]
What kahlan version, php version and os you're using ? I've tried and working fine with latest kahlan 3.1.15 in mac os in php 7.1: 

```
$ bin/kahlan --no-header --spec=spec/

...............FF..                                               19 / 19 (100%)

toBeAnInstanceOf()
  ✖ it should report the test source line number for false
    expect->toBeAnInstanceOf() failed in `./spec/TestSpec.php` line 12
    
    It expect actual to be an instance of expected.
    
    actual:
      (boolean) false
    expected:
      (string) "Whatever"
```

**Comment by deployable** [comment]
Same versions here, on osx too.
```
→ php -v
PHP 7.1.4 (cli) (built: Apr 14 2017 15:02:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
```
→ grep -A1 'kahlan/kahlan' composer.lock
            "name": "kahlan/kahlan",
            "version": "3.1.15",
```
It's appeared for more test functions than just `toBeAnInstanceOf()`.
I guess I could have done something to this project. Is there any kahlan debug I could enable to help track it down?

**Comment by jails** [comment]
When an exception occurs Kahlan use a pattern option (defined by default here https://github.com/kahlan/kahlan/blob/master/src/Cli/Kahlan.php#L105) and attempt to [find it in the backtrace](https://github.com/kahlan/kahlan/blob/master/src/Analysis/Debugger.php#L248).

So either you are in a situation where `$maxLookup` is too low or there's some special chars in file names which make `preg_match` to fail.

Can you provide a example of `$backtrace` value which fails to focus through `Debugger::focus()` ?

**Comment by deployable** [comment]
Thanks for the pointers @jails. It looks like it's the `/` in the pattern definition then. 

If `--pattern` includes a `/` then the pattern works for limiting what tests run but borks the stack traces. 

    ./vendor/bin/kahlan --no-header --pattern='spec/Suite/*Spec.php'

The same occurs if the `--pattern` is allowed to expand in the shell, it still works for what tests run but then fails to focus the stack traces...

    ./vendor/bin/kahlan --no-header --pattern='spec/Suite/*Spec.php'

The stack trace handling works as expected if I leave the default pattern, or set one without a `/` in it...

    ./vendor/bin/kahlan --no-header --spec=spec/Suite

So `fnmatch` in [`Dir->_include`](https://github.com/kahlan/kahlan/blob/1b9b7e5675275c2d23b35bd2a228d6268bda3bf1/src/Dir/Dir.php#L359) is (obviously) dealing with slashes whereas the processing in 
[`backtraceFocus`](https://github.com/kahlan/kahlan/blob/cee45b95570d104107f58d23fd7ee2f96a7b2492/src/Scope.php#L477) doesn't. Although I thought the quoting with `~` would do? I guess windows paths might make it more complicated again.

**Comment by deployable** [comment]
Oh right, [`preg_quote`](https://secure.php.net/manual/en/function.preg-quote.php) doesn't do what I thought it did.

**Comment by jails** [comment]
Hmm, default `--pattern` option should just work fine.
Just curious, what the backtrace look like when you leave `--pattern` unchanged ?

**Comment by jails** [comment]
@deployable any news on this issue ?

**Comment by deployable** [comment]
I believe it's any characters before the wildcard in the `--pattern` argument causes the stack traces to fail. 

It looks like it might be the regex processing in [`focus`](https://github.com/kahlan/kahlan/blob/3a48a2e638e31dca1427dd5ae38640b621e8eb3a/src/Analysis/Debugger.php#L248), the pattern is pinned to the start of the regex string with `^` so it only works when a wildcard is first in the pattern?

**Comment by jails** [comment]
Ah ok, I think I get what you are talking about. The `--pattern` option is used to identify file names. You can't use a path as pattern. So `--pattern=spec/Suite/*Spec.php` is not a valid file name pattern. If your specs aren't located in the `spec` directory you must use the `--spec` option to define the spec directory path. `--pattern` is only intended to be `'*Spec.php'`, `'*.spec.php'`, `'*Test.php'` or whatever pattern identifying spec file names.

**Comment by deployable** [comment]
Yeah, the confusion was due to the `--pattern=spec/whatever/*Spec.php` option actually working correctly as a file filter.

The other way people might get caught out with the `--pattern` is if they were to prefix files with a common string, like `UnitClassSpec.php` but that might be a Node-ish thing I've brought across rather than something a PHPer might try.
