### ISSUE TITLE
Unexpected results when throwing errors

### ISSUE THREAD

**Issue by jhabdas** [kahlan/kahlan#253]
Given the following test:

```php
it('errors if not given an instance', function () {
  $closure = function () {
    get_dep_for_handle(null, 'baz');
  };
  expect($closure)->toThrow();
});
```

Applied against the following code:

```php
function get_dep_for_handle( $instance, $handle ) {
	return $instance->registered[ $handle ];
}
```

The test passes as one would expect. But test also passes with:

    expect($closure)->toBeTruthy();

Which is unexpected.

**Comment by jails** [comment]
Closures are only executed only with the `toThrow` matcher. For other matchers there are simply treated as some raw value.
So in this case `function(){} == true` is correct.

**Comment by jhabdas** [comment]
> Closures are only executed only with the `toThrow` matcher.

What about `toEcho`?

**Comment by jhabdas** [comment]
Consider also the following likely scenario:

```php
it('does not error if handle is registered', function () {
  $dependencies = $this->dependencies;
  $dependencies->registered = ['foo' => 'bar'];
  $closure = function () use ($dependencies) {
    get_dep_for_handle($dependencies, 'foo');
  };
  expect($closure)->not->toThrow(); // => pass
  expect($closure)->toBeEmpty(); // => fail
});
```

In this case Kahlan is more verbose about why the failure occurs. But in the OP, which is somewhat contrived I admit, it seems easy to fall into the trap.

On a somewhat related note I opened the following against the docs due to some false positives I was seeing. It feels like there may be some room for improvement in this area. Unfortunately I don't have enough experience yet with Kahlan to have an opinion.
