### ISSUE TITLE
Unexpected results from toBeCalled

### ISSUE THREAD

**Issue by jhabdas** [kahlan/kahlan#254]
Given the following example from the [Matchers documentation](https://kahlan.github.io/docs/matchers.html):

```php
it("expects `time()` to be called and followed by `rand()`", function() {
    $foo = new Foo();
    expect('time')->toBeCalled()->ordered;
    expect('rand')->toBeCalled()->ordered;
    $foo->date();
    $foo->random();
});
```

To create the following reduced test case:

```php
it('expects to be sorted before checking if its an array', function () {
  function _generate_antimatter () {
    $antiparticles = [];
    array_multisort( $antiparticles );
    is_array( reset( $antiparticles ) );
    return $antiparticles;
  }
  expect('array_multisort')->toBeCalled()->ordered;
  expect('is_array')->toBeCalled()->ordered;
  _generate_antimatter($this->dependencyWithoutQuery);
});
```

Results in the following unexpected output in Kahlan 3.1.15:

```
It expect actual to be called.
 
 actual:
   (string) "array_multisort()"
 actual called times:
   (integer) 0
 expected to be called:
   (string) "array_multisort()"
 
 expect->toBeCalled() failed in `./spec/hyperdrive.spec.php` line 81
 
 It expect actual to be called.
 
 actual:
   (string) "is_array()"
 actual called times:
   (integer) 0
 expected to be called:
   (string) "is_array()"
```

**Comment by samsonasik** [comment]
your `_generate_antimatter ()` function must be inside class that registered in composer autoload to do that test

**Comment by jhabdas** [comment]
PHP introduced function imports in PHP 5.6 near the end of 2015. I realize not every is jumping on procedural programming, but I chose Kahlan because it's gotten me extremely far in my procedural codebase thus far.

Based on my survey of the PHP testing landscape Kahlan was the best I could do to achieve the 74% percent test coverage for thus far, and as discussed in related issues I'm using `file` autoload, which I understand is a kludge in Composer.

That said, I do not plan to do any OOD in my codebase. That means to `class` or `extends` keywords unless I'm doing mocks and have no other choice. I suppose it's up to the creators of Kahlan if it's within the purview of their vision for the progression of Kahlan as to whether or not it will at some point facilitate procedural programming using PHP 5.6 features.

**Comment by jhabdas** [comment]
Closing as this usage is not covered under the current codebase. I may use it in a future issue against Composer if that's the hold-up. To me it's not clear. But what I do know is many use classes in PHP for faux namespaces and that seems night right given PHP's new digs.
