### ISSUE TITLE
Stubs are not cleared after class stubbing in beforeAll

### ISSUE THREAD

**Issue by pawelwnuq** [kahlan/kahlan#255]
I have two specs:
````
// src/Test.php
class Test {
    public function doSomething()
    {
        return "real response";
    }
}

// spec/FirstSpec.php
describe('test', function () {
    beforeAll(function () {
        allow(\Test::class)->toReceive('doSomething')->andReturn('fake response');
    });
});

// spec/SecondSpec.php
describe('test', function () {
    fit('should not be fake', function () {
        $testSubject = new Test();
        expect($testSubject->doSomething())->toBe('real response');
    });
});
````

As you probably know doSomething returns 'fake response'. Probably beforeAll is not meant to stub classes, but In our case it really makes sense to have a function firing once before all specs in DESCRIBE.

**Comment by jails** [comment]
Thanks, will look into it !

**Comment by jails** [comment]
Sorry for the delay, it's fixed in the dev branch https://github.com/kahlan/kahlan/commit/b4f9c8727959279192896bbbb31a963b780aa935. I'll tag a new release soon !
