### ISSUE TITLE
Resetting Doubled classes?

### ISSUE THREAD

**Issue by Ilyes512** [kahlan/kahlan#262]
Hey,

I got some unexpected behaviour when I do the fallowing within a describe->describe->it closure:

```php
// ...
$jwtAuthenticatorDouble = Double::instance(['class' => JwtAuthenticator::class]);
// ...
```

Every fallowing test (a it closure) that create a instance of JwtAuthenticator will be a double instead of the real thing. I expected only `$jwtAuthenticatorDouble` to be a double but not overwrite the really class.

I could do the fallowing:

```
$jwtAuthenticatorDouble = Double::instance(['extends' => JwtAuthenticator::class]);
```

But then I also need to provide the __construct dependencies. Is there a way of creating a instance of a class with defining the construct parameters on which I can then add expectations.

**Comment by samsonasik** [comment]
You may need to write like the following: 

```php
$jwtAuthenticatorDouble = Double::instance([
     'extends' => JwtAuthenticator::class,
     'methods' => '__construct'
]);
```

**Comment by jails** [comment]
The `'class'` option is the class name you want for the double instance. And the fact that once you define a function/class in PHP it stays defined forever, there's no way to "delete it". So `'extends'` is the way to go.

For your example there's two way to do it. You can either stub the `__construct` method like in the @samsonasik example to simply ignore it.

Or if you need to pass real parameters you can do:
```php
$JwtAuthenticatorDouble = Double::classname(['extends' => JwtAuthenticator::class]);
$jwtAuthenticatorDouble = new $JwtAuthenticatorDouble($arg1, $arg2, ...);
```

**Comment by Ilyes512** [comment]
@samsonasik That's idd what I just did, but not the nicest way of writing it :)
