### ISSUE TITLE
Setting times()/once() on allow() chain

### ISSUE THREAD

**Issue by Ilyes512** [kahlan/kahlan#263]
Hey,

I got a question about setting up expectations with defined returns. Is it possible to do the below without much duplication. If I could set a once()/times() inside the allow() chain that would be helpful. 

```php
    describe('authenticateRequest() method', function () {
        it('calls JwtAuthenticator and sets the JwtToken', function () {
            allow($this->authenticator)
                ->toReceive('getJwtToken')
                ->andReturn('JWT_TOKEN');

            allow($this->jwtAuthenticator)
                ->toReceive('setJwtToken', 'authenticateRequest')
                ->where([
                    'setJwtToken'         => ['JWT_TOKEN'],
                    'authenticateRequest' => [$this->requestDouble],
                ])
                ->andReturn($this->requestDouble);

            expect($this->authenticator)
                ->toReceive('getJwtToken')
                ->once();

            expect($this->jwtAuthenticator)
                ->toReceive('setJwtToken', 'authenticateRequest')
                ->where([
                    'setJwtToken'         => ['JWT_TOKEN'],
                    'authenticateRequest' => [$this->requestDouble],
                ])
                ->once();

            expect($this->authenticator->authenticateRequest($this->requestDouble))
                ->toEqual($this->requestDouble);
        });
    });
```

**Comment by jails** [comment]
I personally would remove:
```php
expect($this->authenticator)
    ->toReceive('getJwtToken')
    ->once();

expect($this->jwtAuthenticator)
    ->toReceive('setJwtToken', 'authenticateRequest')
    ->where([
        'setJwtToken'         => ['JWT_TOKEN'],
        'authenticateRequest' => [$this->requestDouble],
])
->once();
```
Since it doesn't add a lot of value because of `allow()` definitions. And checking that a method has been called `->once()` is not the way to go imo. I prefer testing code's behavior which is more resilient to changes that testing code's implementation. So I would instead write a test that check data states proving things actually worked as expected.

**Comment by Ilyes512** [comment]
Not always sure what to test for. For example I got a JwtAuthenticator and a CachedJwtAuthenticator. I am currently testing CachedJwtAuthenticator. It basically just add's a cache check:

```php
    public function getJwtToken()
    {
        if ($this->cache->has(self::JWT_TOKEN_KEY)) {
            return $this->cache->get(self::JWT_TOKEN_KEY);
        }

        $token = $this->jwtAuthenticator->getJwtToken();

        // todo Read the contents of the token to find out how long the token is valid for.
        $this->cache
            ->add(self::JWT_TOKEN_KEY, $token, self::JWT_TOKEN_CACHE_DURATION);

        return $token;
    }

    /**
     * Should be the same as getJwtToken
     */
    public function getJwtToken2()
    {
        return $this->cache
            ->remember(self::JWT_TOKEN_KEY, self::JWT_TOKEN_CACHE_DURATION, function () {
                return $this->jwtAuthenticator->getJwtToken();
            });
    }
```

`$this->cache` is a double based on a contract:

```php
        $this->cache            = Double::instance([
            'implements' => Factory::class,
        ]);
```
(Factory = use Illuminate\Contracts\Cache\Factory;)

I could use the actual cache and set the driver to "array" instead of something like "Redis". I could then add two test that would "test" the Iluminate\Cache components behaviour of "->remember()".

Sometimes I think it's easier to be less pure and indirectly test external components then to mock everything. Not sure... :/

**Comment by jails** [comment]
Not sure to get everything here but if you need to check your cache is hit I would probably simply stubbing your cache `has`/`get` method. The main idea is to expect that the `getJwtToken()` return value is correct instead of expected that your cache `has`/`get` method has been called once with the correct args.
