### ISSUE TITLE
Fail to open stream, file is not copied

### ISSUE THREAD

**Issue by Th3Mouk** [kahlan/kahlan#270]
Hi @jails 

I'm migrating my test suite to Kahlan but all of test suite needs JSON fixtures.
I got the error
```
file_get_contents(/private/var/folders/qr/lmjssp1d16l91lz29kxybbxr0000gn/T/kahlan/Users/Jeremy/Github/iv/src/Extractors/../../datas/fixtures.json): failed to open stream: No such file or directory"
```

Actually i got 3 folders: src, datas, and tests
I tried to personalize the configuration with a kahlan-config.php file to add the different paths.

```
<?php

$commandLine = $this->commandLine();
$commandLine->option('src', ['array' => true, 'default' => ['src', 'datas']]);
$commandLine->option('spec', ['array' => true, 'default' => ['tests']]);
```

All are loaded when I start kahlan
src directory  : /Users/Jeremy/Github/iv/src, /Users/Jeremy/Github/iv/datas
spec directory : /Users/Jeremy/Github/iv/tests

But the tests are launch from `/private/var/folders/qr/lmjssp1d16l91lz29kxybbxr0000gn/T/kahlan/Users/Jeremy/Github/iv` and when I make a `ls` command on this folder there is only `src` and `vendor` folders. No trace of the `datas` folder.

Any miss configuration ? 

Thanks for your help

**Comment by jails** [comment]
Would it be possible to have a sample repo ? For example one test with one src file and one loaded json so I can check everything is setted correctly ?

**Comment by Th3Mouk** [comment]
Sure thanks: https://github.com/Th3Mouk/kahlan-fixtures

**Comment by jails** [comment]
Thank you for the detailed example :+1: 
It was related the `__DIR__` magic constant which wasn't correctly rebased when used outside method's body.
Just fixed it in [3.1.18](https://github.com/kahlan/kahlan/commit/9b233368aa1fecdb284ba7be7b5af6455962bd7e) release.

**Comment by Th3Mouk** [comment]
Thanks ! I will have a look in few minutes

**Comment by jails** [comment]
Once `composer udpate` runned, don't forget to remove cache files in your `/private/var/folders/qr/lmjssp1d16l91lz29kxybbxr0000gn/T/kahlan/Users/Jeremy/Github` folder.

**Comment by Th3Mouk** [comment]
Now it's weird because i'm in 3.1.18 and I just follow your tips but none of my projects can open the json. Nothing relative to my config ?

**Comment by jails** [comment]
You can remove `$commandLine->option('src', ['array' => true, 'default' => ['src', 'datas']]);` from `kahlan-config.php` and just updated the path in `Extractor.php` from `__DIR__.'/../../datas/datas.json';` to `__DIR__.'/../datas/datas.json';` to make your example to pass locally.

**Comment by Th3Mouk** [comment]
Yes the example path was wrong due to simplication, cleaning the whole `private/var/folders/qr/lmjssp1d16l91lz29kxybbxr0000gn/T/kahlan` resolve all other projects thank you very much have a nice sunday

**Comment by jails** [comment]
You bet !
