### ISSUE TITLE
Not memoized given()

### ISSUE THREAD

**Issue by Isinlor** [kahlan/kahlan#272]
Sometimes when I need to test a composite I want to provide more than one double. The current behavior of the given helper forces me to either copy&paste the code or do some work around like creating an anonymous function factory.

```php
   given('factory', function () {
        return function () {
            return new class implements Contract
            {
                //some implementation that I can use for testing
            };
        };
    });

    given('collection of elements', function () {
        $factory = $this->factory;

        return [
            $factory(),
            $factory(),
            $factory(),
        ];
    });
```

Is there some better approach?

**Comment by jails** [comment]
Just looked at [RSpec](https://relishapp.com/rspec/rspec-core/v/3-4/docs/helper-methods/let-and-let) and looks like they doesn't support "not memoized" helper and consider them as arbitrary helpers instead.
So maybe the best option here it too use simple function for creating not memoized instances ?

**Comment by jails** [comment]
After thinking about it, introducing such behavior must be done without making variables manipulation confusing. For example if we are using a similar syntax for both memoized and not memoized variables we would reach weird situations:

```php
$value1 = $this->memoized;
$value1 = $this->memoized; // Same value as above
$valueA = $this->notMemoized;
$valueB = $this->notMemoized; // Different value as above
```
In the example above it makes no sense that hitting the same variable twice generate two different values. And I'm also agree that using `given()` for both defining simple values as well as factories is a bit miss leading.

So for such use case I would intoduce a new statement like so:

```php
    given('myvar', function () {
        return new class implements Contract
        {
            //some implementation that I can use for testing
        };
    });

    given('collection of elements', function () {
        return [
            build('myvar'),
            build('myvar'),
            build('myvar'),
        ];
    });
```
With the `build()` function defined in `kahlan-config.php` like so:

```php
function make($name)
{
    $current = Suite::current();
    $value = $current->scope()->{$name};
    return new $value();
}
```
