### ISSUE TITLE
Use English abbreviations for memory usage statistics?

### ISSUE THREAD

**Issue by ezzatron** [kahlan/kahlan#275]
This is definitely not a big deal, but I was always curious about the "using 7Mo" until I figured out that this was a French abbreviation for megabyte, and then I realised that it's obviously the memory usage.

Since the rest of your interface is in English, it might be less confusing for new users to see standard English abbreviation for byte amounts (B, KB, MB, GB), or even the unambiguous IEC binary abbreviations (B, KiB, MiB, GiB).

...or maybe it's just a cool little reminder of the French origins of Kahlan 🇫🇷😄🇫🇷

I don't know, but I thought it probably deserves a discussion.

**Comment by jails** [comment]
Thanks for the head up ^^
Thought it was also [used in english](https://en.wikipedia.org/wiki/Octet_(computing))

Sure let's for for a B.
Hopefully I didn't tag the 4.0 yet :-p

**Comment by jails** [comment]
Fixed in https://github.com/kahlan/kahlan/commit/1edbcb3443a2bdb4b1df30b57f4a69a1c27c575f

**Comment by ezzatron** [comment]
@jails FYI, the old abbreviations still seem to be used for code coverage:

```
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The PHP Test Framework for Freedom, Truth and Justice.

src directory  : ./src
spec directory : ./spec

...............                                                   15 / 15 (100%)



Expectations   : 42 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 15 of 15 PASS in 0.044 seconds (using 6MB)

Coverage Summary
----------------
                                                Lines            %

 \                                             20 / 20     100.00%
├── EventEmitter                               13 / 13     100.00%
│  ├── EventEmitter::emit()                     1 /  1     100.00%
│  ├── EventEmitter::listeners()                2 /  2     100.00%
│  ├── EventEmitter::on()                       2 /  2     100.00%
│  ├── EventEmitter::once()                     4 /  4     100.00%
│  ├── EventEmitter::removeAllListeners()       2 /  2     100.00%
│  └── EventEmitter::removeListener()           2 /  2     100.00%
└── Example\                                    7 /  7     100.00%
   └── Dns\                                     7 /  7     100.00%
      └── DomainResolver                        7 /  7     100.00%
         ├── DomainResolver::__construct()      1 /  1     100.00%
         └── DomainResolver::resolve()          6 /  6     100.00%

Total: 100.00% (20/20)

Coverage collected in 0.007 seconds (using an additional 50Ko)
```

**Comment by samsonasik** [comment]
@ezzatron I've created PR https://github.com/kahlan/kahlan/pull/276 for it
