### ISSUE TITLE
Problems with including files by relative paths in 4.0.0

### ISSUE THREAD

**Issue by tyranron** [kahlan/kahlan#278]
In one of my project I have a file `src/setup.php` which contains (for some reasons) line like:
```php
require_once 'Conf.php';
\MyProj\Conf::parseFromFile();
```
The file `src/Conf.php` is located in the same directory as `src/setup.php` (it's `src/` directory Captain Obvious said 🤠).

When running specs with `4.0.0` Kahlan release it fails with the following error (it was OK on `3.x` branch):
```
[PHP Warning:  Uncaught ErrorException: require_once(Conf.php): failed to open stream: No such file or directory in /tmp/kahlan/app/src/setup.php:22
Stack trace:
#0 /tmp/kahlan/app/src/setup.php(22): Kahlan\Jit\ClassLoader->{closure}(2, 'require_once(Co...', '/tmp/kahlan/app...', 22, Array)
#1 /tmp/kahlan/app/src/setup.php(22): require_once()
#2 /usr/src/kahlan-4.0.0/src/Jit/ClassLoader.php(246): require('/tmp/kahlan/app...')
#3 /usr/src/kahlan-4.0.0/bin/kahlan(46): Kahlan\Jit\ClassLoader->loadFile('/app/src/setup....')
#4 {main}
  thrown in /tmp/kahlan/app/src/setup.php on line 22]
[PHP Fatal error:  Kahlan\Jit\ClassLoader::main(): Failed opening required 'Conf.php' (include_path='.:/usr/local/lib/php') in /tmp/kahlan/app/src/setup.php on line 22]
```

If I do the change:
```patch
- require_once 'Conf.php';
+ require_once __DIR__.'/Conf.php';
```
It runs OK.

Also:  
The file `src/setup.php` is declared in `autoload` section of `composer.json`:
```json
  "autoload": {
    "psr-4": {
      "MyProj\\": "src/"
    },
    "files": [
      "src/setup.php"
    ]
  },
```

**Comment by jails** [comment]
Indeed now auto-loaded files are JIT patched so they are loaded from the `/tmp/kahlan` which was a BC break. It should be fixed in https://github.com/kahlan/kahlan/commit/4cf22224df11b11bd60370ff35cf37daee72bc59
