### ISSUE TITLE
Allow error supression with @

### ISSUE THREAD

**Issue by Khartir** [kahlan/kahlan#279]
Currently it is not possible to test code, that relies on the Error Control Operator `@`. This is due to the fact that this operator still calls the custom error handling function and only changes the value of `error_reporting()` to 0.
I would therefore suggest that the default error handler checks if error_reporting is set to 0 and if so, doesn't throw a `PhpErrorException`.

**Comment by jails** [comment]
Closing in flavor of https://github.com/kahlan/kahlan/pull/280
