### ISSUE TITLE
More docs on Filters?

### ISSUE THREAD

**Issue by tsunamilx** [kahlan/kahlan#286]
I am trying to update the laravel integration which is now unmaintained, since 4.0 released with the api change of filters, I dont understand how filters work, when filters are called, etc...

**Comment by jails** [comment]
Hello,
Filters behave like middlewares. They are used to change a method's behavior with some custom code. You can find more details about it [right there](https://github.com/crysalead/filter).

You can easily update the syntax from kahlan 3.x to a kahlan 4.x version by removing the registration step, using `Filters` instead `Filter` and using `'bootstrap'` intead of `'interceptor'` as entry point in a `kahlan-config.php` file for example.

Old syntax:
```php
use Kahlan\Filter\Filter;

Filter::register('something', function ($chain) {
    // the filter logic
    return $chain->next();
});
Filter::apply($this, 'interceptor', 'something');
```

New Syntax:
```php
use Kahlan\Filter\Filters;

Filters::apply($this, 'bootstrap', function ($chain) {
    // the filter logic
    return $chain->next();
});
```

**Comment by tsunamilx** [comment]
OK I figured out how it works, thanks!
