### ISSUE TITLE
Feature request: match call of variable functions

### ISSUE THREAD

**Issue by Khartir** [kahlan/kahlan#291]
Currently it is not possible to use the toBeCalled matcher to verify the calling of a variable function or a function called with call_user_func.
Example code:
```php
describe('callback matching', function () {
    beforeAll(function() {
        $this->c = new Caller();
    });
    it('works with direct function call', function () {
        //works
        expect('time')->toBeCalled();
        $this->c->direct();
    });
    it('works with variable function call', function () {
        //doesn't work
        expect('time')->toBeCalled();
        $this->c->variable('time');
    });
    it('works with call_user_func', function () {
        //doesn't work
        expect('time')->toBeCalled();
        $this->c->call_user_func('time');
    });
    it('works with indirect test for call_user_func', function () {
        //works
        expect('call_user_func')->toBeCalled()->with('time');
        $this->c->call_user_func('time');
    });
});
```
with class:
```php
class Caller {

    public function direct() {
        time();
    }

    public function variable($name) {
        $name();
    }

    public function call_user_func($name) {
        call_user_func($name);
    }
}
```

The indirect test for call_user_func works of course and is a valid workaround but it would be nice if it wasn't necessary. And as mentioned it's impossible to check variable functions. From a quick look I'd say that's because something like `time()` get's patched, where as something like `$name()` doesn't.

**Comment by jails** [comment]
Thank you for your request. Unfortunately the Khalan JIT patching occurs when the code is loaded. So there's no really way to support that since variables values are only available at runtime.
