### ISSUE TITLE
Please remove unicode chars from reporter

### ISSUE THREAD

**Issue by jetiny** [kahlan/kahlan#292]
![image](https://user-images.githubusercontent.com/7445506/36944876-912755b8-1fdf-11e8-8d9d-893291acace1.png)

**Comment by jails** [comment]
What alternative do you suggest ?

**Comment by jetiny** [comment]
I have test  char `-` , how does it look like ? @jails 

![image](https://user-images.githubusercontent.com/7445506/36952923-bf18cbca-2050-11e8-9586-9c78ab42d29b.png)

![image](https://user-images.githubusercontent.com/7445506/36952905-913db09e-2050-11e8-8623-bc47257ad253.png)

**Comment by jetiny** [comment]
``` php
    protected function _renderMetricsReport()
    {
            $isLast = $index === $nbChilden - 1;
            if ($isLast) {
                $this->_prefixes[$depth] = '└──'; // replaced with '-'
            } else {
                $this->_prefixes[$depth] = '├──'; // replaced with '-'
            }
            // ...
            if ($isLast) {
                $this->_prefixes[$depth] = '   '; // replaced with  '  ' 2 space
            } else {
                $this->_prefixes[$depth] = '│  '; // replaced with  '  ' 2 space
            }
    }
```

I sugguest you useing the `TERM` code in Terminal.php

```php
        $term = getenv('TERM');
        if (getenv('COLORTERM') || preg_match('~screen|^xterm|^vt100|color|ansi|cygwin|linux~i', $term)) {
            $this->_colors = true;
            return $this;
        }
```

**Comment by jails** [comment]
A couple of linux commands are already relying on these characters (e.g. the `tree` command).
How comes these UTF-8 characters are not supported ? Is it a windows related issue ?

**Comment by jails** [comment]
After thinking about it, I think UTF-8 is a widespread enough standard to not degrade reports for specific terminals.
