### ISSUE TITLE
Debug ?

### ISSUE THREAD

**Issue by MatthD** [kahlan/kahlan#298]
Hello,

I use your unit test framework & I would like to debug my test script with my IDE,

How should I do ? Xdebug ? (I am using phpstorm)

**Comment by jails** [comment]
Sorry I'm not using phpstorm, @phishy willing sharing your secrets ? :stuck_out_tongue:

**Comment by MatthD** [comment]
Ah np, my question is large, if I can debug with any other editor/ide It would be ok for me ;)

**Comment by phishy** [comment]
I followed this. https://confluence.jetbrains.com/plugins/servlet/mobile#content/view/57288880

**Comment by MatthD** [comment]
Ok so I got it to work,
that is the configuration to be able to debug khalan on phpstorm (for all test files)
There is two important thing, the /vendor/bin/kahlan IS the script & path must be absolute not relative, then you have to say to phpsorm the custom directory (the current project)

![test](http://image.noelshack.com/fichiers/2018/15/6/1523729441-capture-d-ecran-2018-04-14-a-20-08-55.png)

**Comment by jails** [comment]
Thank you for sharing :+1:
