### ISSUE TITLE
expect('time')->toBeCalled()->once(); not work at v4.1

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#300]
while the `time()` called internally in function class, it was actually working to use the expect : 

```php
$expected = 1477897159;

allow('time')->toBeCalled()->andReturn($expected);
expect('time')->toBeCalled()->once();
```

**Comment by jails** [comment]
Thanks for the report man !
It should have been fixed in https://github.com/kahlan/kahlan/commit/6390dea0898454d02a2183f75081ff8939eb10bf
