### ISSUE TITLE
Growl notifications?

### ISSUE THREAD

**Issue by rapodaca** [kahlan/kahlan#302]
Does Kahlan support Growl notifications?

I'm interested in a workflow on OSX in which my tests run when I save files, then a notification is presented about passing/failing tests.

I was able to get watchman-make to  auto-run tests like this:

```
watchman-make -p '**/*.php' --run vendor/bin/kahlan
```

**Comment by jails** [comment]
You may use the following `kahlan-config.php` file to run something when specs passed/failed.

```php
<?php
use Kahlan\Filter\Filters;

/**
 * Boostraping & running the specs
 */
Filters::apply($this, 'run', function($next) {
    // Run Kahlan specs
    $result = $next();

    if ($this->suite()->summary()->passed()) {
        // Run something on success
    } else {
        // Run something on failure
    }
    return $result;
});
```
So if you find a command-line utility which is able to send some kind of growl notifications on OSX, you are good to go.
