### ISSUE TITLE
PSR code style?

### ISSUE THREAD

**Issue by ddziaduch** [kahlan/kahlan#305]
Hi.

Why Kahlan do not follow PSR code style?

**Comment by jails** [comment]
Hello, as far as I can tell Kahlan follows all PSR-2 "MUST" rules so it should be PSR-2 compliant.

**Comment by ddziaduch** [comment]
@jails you are right! My bad. I thought that PSR-2 disallow of underscored private properties in the classes. But that is not true :) Closing!
