### ISSUE TITLE
Double::instance(['methods' => ....]) improvements

### ISSUE THREAD

**Issue by ddziaduch** [kahlan/kahlan#307]
Today I figured out that it would be great to configure doubles like this:
```php
<?php
$double = Double::instance(['extends' => \PDO::class', 'methods' => [
  '__construct' => function () {}, // this function should be called instead of regular constructor
  'query' => false // query method will always return false
]]);
```
So in this line you set up a Double of \PDO with two methods:
- fake constructor
- query method which will return false

What do you think guys? :) The only problem I see is when you would like to make a function to return another lambda

**Comment by blazej-pachut-gforces** [comment]
I would dump "class" since we already have "extends" or "implements" but having a way to quickly define allows as a assoc array would be really nice.

**Comment by jails** [comment]
Instead of :
```php
$double = Double::instance(['extends' => \PDO::class, 'methods' => ['__construct']]);
allow($double)->toReceive('query')->andReturn(false);
```

you mean ?

**Comment by ddziaduch** [comment]
@jails yeap

**Comment by jails** [comment]
Fixed in https://github.com/kahlan/kahlan/commit/16812c8584eea7afb644fcf924fe9dada102adce
