### ISSUE TITLE
Incorrect code coverage for string variable block

### ISSUE THREAD

**Issue by chrisleekr** [kahlan/kahlan#308]
My code contains the text variable like below:
```php
<?php 
class Temp
{
    public static function process(){
        $text = "
            This is test
        ";

        return $text;
    }
}
```

And my test is like below
```php
<?php
describe("Test functions", function () {
        it("should return text", function () {
            $expected = "This is test";
            expect(trim(Temp::process()))->toBe($expected);
        });
});
```

The test is succeed; however, code coverage shows incorrect value like below due to second quotation mark. 

![image](https://user-images.githubusercontent.com/5715919/44499587-e0802f80-a6c7-11e8-8e7d-95bed12a7d0d.png)

Is this known bug?

**Comment by jails** [comment]
Thanks for the report :+1: 
Actually the main coverage issues rely on phpdbg/xdebug code coverage results which contains a lot of inconsistencies. I guess it's inherent to PHP since I didn't see something like that in any other languages. Anyway I just added another workaround in 4.1.7.

**Comment by chrisleekr** [comment]
@jails Thanks for fix!!
