### ISSUE TITLE
Use with symphony 4 ?

### ISSUE THREAD

**Issue by MatthD** [kahlan/kahlan#310]
Are some people using it with symfony4, not sure this is possible nowadays.

I would like if someone could post how to use it with..

**Comment by samsonasik** [comment]
@MatthD I created a blogpost about it https://samsonasik.wordpress.com/2018/01/03/functional-test-symfony-4-with-kahlan-4/

**Comment by MatthD** [comment]
Hello @samsonasik yeah I used it to do my first functional test, but what about to test only a simple controller ? Could you provided an exemple ? (I am new to symfony, not to kahlan ;) )
I am not sure about the way to do it correctly (about using namespace ...)

**Comment by ddziaduch** [comment]
@MatthD can you show us the code of your controller?

**Comment by MatthD** [comment]
Yeah, I did it correctly with an 'util' class:


- /src/util/Calculator.php

```php

namespace App\Util;

class Calculator
{
    public function randAndSquare($a=0, $b=100)
    {
    	$rdmNb = random_int($a, $b);
        return $rdmNb * $rdmNb;
    }
}

 ?>
```

- spec/util/CalculatorSpec.php : 

```php
<?php 

namespace App\Spec\Util;
use App\Util\Calculator;

/* This is a sample Unit Test  */
describe('CalculatorUtil', function () {
    describe('randAndSquare', function () {
        it('randAndSquare should return à squared between two number', function () {
            $calcul = new Calculator();
            $nb = $calcul->randAndSquare(4,8);

            expect($nb)->toBeGreaterThan(15);
            expect($nb)->toBeLessThan(65);
        });
    });
});

?>
```

So is it the same for a Controller ?

**Comment by jails** [comment]
Most of the time controllers plugs together different objects and connects them in the correct order. So it all depends of the code you want to test.

If your controller does more than simply plugging stuff you should think about refactoring it's business logic into low-level classes so you can actually unit-tests.

Then if I had to test a controller, I will do it with a functional test. Unit testing a controller is considered as a bad practice by many people.

**Comment by jails** [comment]
Anyway, I think this is more a Symfony4 related question that a Kahlan one so I'm closing this issue.
