### ISSUE TITLE
property based testing

### ISSUE THREAD

**Issue by marcosh** [kahlan/kahlan#312]
I think it would be really nice to integrate `kahlan` with [Eris](https://github.com/giorgiosironi/eris) or some other library with provides generation of random data, to allow property based testing in a [QuickCheck](https://github.com/nick8325/quickcheck) style.

Would it be something feasible/desirable?

**Comment by jails** [comment]
Kahlan can already be extended in multiple ways so I guess `Eris` should work out of the box by simply converting `https://github.com/giorgiosironi/eris/blob/master/src/TestTrait.php` so it doesn't rely on PHPUnit.

**Comment by angelxmoreno** [comment]
@marcosh I used [Faker](https://github.com/fzaninotto/Faker) with [FactoryMuffin](https://github.com/thephpleague/factory-muffin) in the past with great success

**Comment by jails** [comment]
Anyway, I'm open for core changes or PR if the current Kahlan plugin system doesn't allow enough interoperability with some external tools.
