### ISSUE TITLE
Specs sorting

### ISSUE THREAD

**Issue by ddziaduch** [kahlan/kahlan#313]
Morning.

Is it possible to sort all specs before running them? This should be an option and should be set to false as default. What do you think guys?

**Comment by jails** [comment]
In 4.3 the top most describe statements of each spec files are now sorted according an arbitrary order so it doesn't depends on the file system ordering anymore. Then all specs inside a spec file are just executed according to their position in the file.
What kind of additional ordering are you thinking about ?

**Comment by ddziaduch** [comment]
I didn't know about that, thanks @jails 

Closing.
