### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by ddziaduch** [kahlan/kahlan#317]
Hello.

7.3 is currently as RC. Do we need to amend the code to support 7.3? Changes are not so big:
https://kinsta.com/blog/php-7-3/

**Comment by samsonasik** [comment]
I've applied at #318

**Comment by samsonasik** [comment]
The php 7.3 env registered at travis at #318

**Comment by ddziaduch** [comment]
Cool beans @samsonasik
