### ISSUE TITLE
Incorrect coverage summary 

### ISSUE THREAD

**Issue by chrisleekr** [kahlan/kahlan#319]
Hi,

I found Kahlan shows incorrect coverage lines for some code structure.
I encountered this issue with another project; and I could reproduce with below sample code.

- LongCode.php: has function `testA`
- LongCode.spec.php: calls `testA` in `beforeAll`.

I attached a sample code and screenshot of the result.
If you want, I can provide actual code.

I found if I change `beforeAll` to `beforeEach`, shows coverage.

Does it mean a code executed with `beforeAll` won't be covered by Kahlan?

**composer.json**
```json
{
    ...
  "require": {
    "php": "7.2",
    "slim/slim": "^3.1",
    "monolog/monolog": "^1.17",
    "php-ds/php-ds": "*",
    "ext-PDO": "*"
  },
  "require-dev": {
    "phpunit/phpunit": "^7",
    "squizlabs/php_codesniffer": "^3.1",
    "phploc/phploc": "^4.0",
    "phpunit/php-code-coverage": "^6",
    "phan/phan": "^0.12.9",
    "kahlan/kahlan": "^4.1.3",
    "kahlan/extra-matcher": "^1.0"
  },
  "autoload": {
    "psr-4": {
      "KahlanTest\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "KahlanTest\\Tests\\": "tests/"
    }
  },
  ...
}

```

**LongCode.php**
```php
<?php
namespace KahlanTest;

use Ds\Map;

class LongCode
{
    public static function processValue(Map $row)
    {
        return $row;
    }

    public static function testA(int $user_id):Map
    {
        $pdo = new \PDO(
            "mysql:host=localhost:3307;dbname=kahlan_test;",
            "root",
            "root"
        );

        $query = "
            SELECT
                id
            FROM
                user
            WHERE
                user_id = :user_id
        ";

        $statement = $pdo->prepare($query);
        $statement->bindValue(':user_id', $user_id);
        $statement->execute();
        $row = $statement->fetch(\PDO::FETCH_ASSOC);
        $statement->closeCursor();

        if (empty($row)) {
            return new Map([]);
        }

        return self::processValue(new Map($row));
    }
}
```

**LongCode.spec.php**
```php
<?php

use KahlanTest\Temp;
use KahlanTest\LongCode;

describe("TestA", function () {
    beforeAll(function () {
        $this->user = LongCode::testA(1);
    });

    it("should not return user", function () {
        expect($this->user->toArray())->toBe([]);
    });
});

```

![screen shot 2018-11-06 at 10 29 17 pm](https://user-images.githubusercontent.com/5715919/48061645-d1634500-e213-11e8-91c8-a4e81a00a08b.jpg)

**Comment by jails** [comment]
Hi,
Thanks for the detailed example.

Since `beforeEach()` & `beforeAll()` are simple initialization steps, only the code ran in `it()` function (i.e containing `expect()` statements proving that the ran code is "under control") are included in the coverage results.

This choice has been made by design but it was quite an arbitrary decision at that time.

so:
```php
<?php

use KahlanTest\Temp;
use KahlanTest\LongCode;

describe("TestA", function () {
    beforeAll(function () {
    });

    it("should not return user", function () {
        $this->user = LongCode::testA(1);
        expect($this->user->toArray())->toBe([]);
    });
});

Should make your code covered.

**Comment by chrisleekr** [comment]
Hi @jails 

Right. I am using `beforeAll()` frequently to avoid duplicated initialization steps.
However, if this is a design choice, I should put them in `beforeEach()` or `it()`

But I think if you are including `beforeEach()` to coverage, then `beforeAll()` should also include into the coverage. Unless there is strict reason to against that pattern. :)

Anyway! Thanks for comment.

**Comment by jails** [comment]
That's a fair point, I'll probably change this behavior then :+1:

**Comment by ddziaduch** [comment]
@jails from what I remember Jasmine gets coverage from the code ran in the `beforeAll()`

**Comment by jails** [comment]
Thanks for the feedback guys :+1:, the behavior has been changed in the 4.4.0 version.
