### ISSUE TITLE
Exclude a folder in code coverage

### ISSUE THREAD

**Issue by sofianebelaribi** [kahlan/kahlan#321]
Hi,
I'm using Kahlan on Symfony 4 for functional & unit tests. This is my code coverage report :

![image](https://user-images.githubusercontent.com/33513415/50293456-e74f6100-0473-11e9-907e-1db25feaaa30.png)

**The thing is that I would like to exclude 'Entity' folder.**
How should I do this ?

Thanks in advance.

**Comment by jails** [comment]
You should be able to set up your custom coverage reporting through a `kahlan-config.php` config file:

```php
<?php
use Kahlan\Filter\Filters;
use Kahlan\Reporter\Coverage;
use Kahlan\Reporter\Coverage\Driver\Xdebug;

Filters::apply($this, 'coverage', function($next) {
    if (!extension_loaded('xdebug')) {
        return;
    }
    $reporters = $this->reporters();
    $coverage = new Coverage([
        'verbosity' => $this->commandLine()->get('coverage'),
        'driver'    => new Xdebug(),
        'path'      => $this->commandLine()->get('src'),
        'exclude'   => [
            'src/Exclude/Fodler1',
            'src/Exclude/Fodler2'
        ],
        'colors'    => !$this->commandLine()->get('no-colors')
    ]);
    $reporters->add('coverage', $coverage);
});
```

**Comment by sofianebelaribi** [comment]
Thank you for your answer for your fast answer, I tried your configuration but it still doesn't work.
This is what I get before applying the filter :

![image](https://user-images.githubusercontent.com/33513415/50335420-8c694880-050b-11e9-9c4d-db92c249f97f.png)

Then I added your filter :

```php
Filters::apply($this, 'coverage', function($next) {
    if (!extension_loaded('xdebug')) {
        return;
    }
    $reporters = $this->reporters();
    $coverage = new Coverage([
        'verbosity' => 2,
        'driver'    => new Xdebug(),
        'path'      => $this->commandLine()->get('src'),
        'exclude'   => [
            'src/Controller/',
            /*'Symfony',
            'Doctrine',
            'MobicoopBundle',
            'Entity',
            'Controller',
            'Mobicoop\Bundle\MobicoopBundle\Entity',
            'Mobicoop/Bundle/MobicoopBundle',
            'src',
            'Controller',
            'src/MobicoopBundle/Entity',
            'MobicoopBundle/Entity',
            'MobicoopBundle',
            'src/MobicoopBundle',*/
        ],
        /*'include'   => [
            'Mobicoop/Bundle/MobicoopBundle',
            'src',
            'Controller',
            'src/MobicoopBundle/Entity',
            'MobicoopBundle/Entity',
            'MobicoopBundle',
            'src/MobicoopBundle',
        ],*/
        'colors'    => !$this->commandLine()->get('no-colors')
    ]);
    $reporters->add('coverage', $coverage);
});
```

Every commented paths are those I tried one by one, but I'm still getting this coverage report with all folders taken into account :

![image](https://user-images.githubusercontent.com/33513415/50335544-ea962b80-050b-11e9-912a-260518c02ac1.png)

It looks like Kahlan doesn't take these paths into account. Or maybe it doesn't find them because when I tried to include some paths i get this :

![image](https://user-images.githubusercontent.com/33513415/50336103-94c28300-050d-11e9-87b8-f5b05099c86d.png)

If that can help :
- this is the command I run : `vendor/bin/kahlan --spec=src/MobicoopBundle/spec src=src/MobicoopBundle --coverage`

- this is src/ tree : 
├───Controller
├───MobicoopBundle
│   ├───Controller
│   ├───Entity
│   ├───Form
│   ├───Service
│   ├───spec
│   │   ├───Controller
│   │   └───Service
│   └───Util
└───Repository

- I'm running another filter in kahlan-config.php in which I use Symfony panther in order to run my functionnal tests.

**Comment by sofianebelaribi** [comment]
Ok, That's perfectly working now, I'm sorry I thought I just had to specify folder path only and not all its content !

**Thank you very much for your time and help I really appreciate it !**
