### ISSUE TITLE
Expecting a function to be called with different argument

### ISSUE THREAD

**Issue by TomPradat** [kahlan/kahlan#322]
I have a function which is called twice, but with different arguments.

```
$api->get('a');
$api->get('b');
```

I'd expect to be able to do something like this :
```
expect($api)->toReceive('get')->with(['a', 'b'])->twice();
```

Is it possible to test this, I couldn't find a way to

**Comment by samsonasik** [comment]
You can use `times()`:

```php 
$gets = ['a', 'b'];
foreach ($gets as $row) {
    expect($api)->toReceive('get')->with($row);
}

expect($api)->toReceive('get')->times(count($gets));
```

**Comment by TomPradat** [comment]
It works like a charm, thank you :), and thanks for answering so quickly.

It makes me wonder if this should be in the documentation.

**Comment by samsonasik** [comment]
You can find in the documentation under `Matchers` https://kahlan.github.io/docs/matchers.html

**Comment by TomPradat** [comment]
I'm sorry i don't see that specific use case in the doc. Maybe having it here is sufficient though

**Comment by ddziaduch** [comment]
If you want to make sure that they are called in a specific order you can achieve that using `->ordered`:
```
expect($api)->toReceive('get')->with('a')->ordered;
expect($api)->toReceive('get')->with('b')->ordered;
```
