### ISSUE TITLE
[Question] Filter to add closure in afterEach as last element (aka. after partition())

### ISSUE THREAD

**Issue by jamesst20** [kahlan/kahlan#323]
Hi,

I would like to add a global closure in afterEach.

Doing this work fine : 
```
 Filters::apply($specs, 'run', function ($next) use ($specs, $instance) {
      $specs->suite()->root()->afterEach(function () {
          $this->laravel->tearDown();
       });

       return $next();
  });
```

However, I would like that `$this->laravel->tearDown();` is called in the very last afterEach.

Looking at the code, I would say that calling this filter right after `\Kahlan\Block\Group#partition` is done executing would probable work.

Is it possible ?

Thank you

**Comment by jails** [comment]
> However, I would like that $this->laravel->tearDown(); is called in the very last afterEach.

If you mean the true last `afterEach()` I guess you should simply use `afterAll()` which is ran once at the very last.
However if you mean the `afterEach()` which occurs at the end of a spec file, I honestly don't know how to identify it.
The "best way" (which doesn't really answer your question) is to probably copy paste your code in all spec files through an `afterEach()` method.
Anyway the "ugly way" could be to use a reporter to execute some piece of code each time you're reaching the end of a spec which only has 1 parent (which is somehow a way to identify the root spec of a file) 

```php
<?php
use Kahlan\Filter\Filters;

$specs = $this;

Filters::apply($this, 'reporters', function($next) {
    $reporters = $this->reporters();
    $reporters->add('teardown', new class() extends \Kahlan\Reporter\Reporter {
        public function suiteEnd($suite = null)
        {
            if (count($suite->parents()) === 1) {
                $suite->scope()->laravel->tearDown();
            }
        }
    });
    return $next();
});
```

**Comment by jamesst20** [comment]
@jails

Thank you I will have a look in the next hour.

What I meant is that if my specs define an afterEach(function(){...}) inside a describe or a context, that afterEach will be executed after the afterEach I registered in the Filter. I would like to have the opposite.

Thank you

**Comment by jamesst20** [comment]
@jails 

Based on your answer, this appear to have the correct behavior :

```

**Comment by jails** [comment]
@jamesst20 sorry I didn't get what you meant first.
I checked the behavior in Rspec and `after` hooks are indeed ran in the opposite way (first declared, last executed).
I just changed the behavior in the new 4.6.0 version to match Rspec's one.
The "ugly hack" I suggested shouldn't be necessary now ;-)

**Comment by jamesst20** [comment]
@jails 

Thank you so much ! Indeed the hack is no longer needed !

I think it makes more sense this way anyway. beforeEach from top to bottom context and afterEach from bottom to top 💯

**Comment by jamesst20** [comment]
@jails 

In case you have access and if you agree, would you be able to update this page https://kahlan.github.io/docs/integration.html to add my new Laravel integration ?

The current integration linked hasn't been updated since PHPUnit 6, Kahlan 3.5 and Laravel 5.5.
My new integration works exclusively with latest PHPUnit 7 (probably 8 too), Laravel 5.8, Kahlan 4.6. https://github.com/jamesst20/kahlan-laravel

I think it's worth linking both :)

**Comment by samsonasik** [comment]
@jamesst20 implemented https://github.com/kahlan/docs/commit/5d20219dfee85d4c482cad1035fbe4920003c51d

**Comment by samsonasik** [comment]
@jamesst20 oh, I forgot to apply 2 links, will fix in the few.

**Comment by samsonasik** [comment]
@jamesst20 docs updated and deployed https://github.com/kahlan/docs/commit/0aeca77ab9160e5e505028e40d820df5849a83aa -> https://kahlan.github.io/docs/integration.html

**Comment by jamesst20** [comment]
Thank you ! :)
