### ISSUE TITLE
[Feature RSpec like] Variables & Functions always scoped to current context

### ISSUE THREAD

**Issue by jamesst20** [kahlan/kahlan#324]
Hi,

I think it would be an awesome feature to have : variables declaration & methods declaration that can be overriden in different context.

Here is an example to make it easier to understand:

```php
describe("something", function() {
    beforeEach(function() {
        $this->post = function() { 
            return $this->laravel->post(route('a.b.c'), $this->parameters);
        };
    });

    context("first", function() {
        beforeEach(function() {
            $this->parameters = array('value' => 'valid');
        });

        it("returns 200 OK", function() {
            $request = $this->post();
            expect($request->getStatusCode())->toEqual(200);
        });
    });

    context("first", function() {
        beforeEach(function() {
            $this->parameters = array('value' => 'invalid');
        });

        it("returns 400 Bad Request", function() {
            $request = $this->post();
            expect($request->getStatusCode())->toEqual(400);
        });
    });
});
```

We currently can make this work by replacing every `$this->post()` call by `$this->post->call($this)` but it would be nicer to have this kind of feature built in like RSpec does.

RSpec example

```ruby
RSpec.describe MyController, type: :controller do
  before(:each) { post :route, params: attributes }

  context "first" do
    let(:attributes) { { value: :valid } }

    it { expect(response).to_not be_successful }
  end

  context "second" do
    let(:attributes) { { value: :invalid } }

    it { expect(response).to_not be_successful }
  end
end
```

Thanks in advance ! :)

**Comment by jails** [comment]
That makes a lot of sense :+1:
I don't know how it should be implemented yet, but I will give it a go !

**Comment by jamesst20** [comment]
@jails

I don't know if it helps, but it seems to me that in RSpec, "let" is probably excuted from top to bottom before "beforeEach" is triggered. 

I havn't checked if the let block is evaluated in case that it isn't used

**Comment by jails** [comment]
Sorry for the delay, this behavior has been added in the 5.0.5 release.
