### ISSUE TITLE
Drop support for older version

### ISSUE THREAD

**Issue by ddziaduch** [kahlan/kahlan#325]
https://www.php.net/supported-versions.php

Kahlan still supports 5.5, what moving to 7.0 or 7.1? Code will be much better with that change

**Comment by ddziaduch** [comment]
Anyone who would like to use Kahlan on older PHP can still use older release of Kahlan 🙂

**Comment by jails** [comment]
Agreed, let's plan that for the 5.0 release :+1:

**Comment by ddziaduch** [comment]
@jails are you working on this? I can help 🙂

**Comment by jails** [comment]
@ddziaduch I didn't started yet :sweat_smile:. But yeah sure, I'm always looking for generous help :+1:

**Comment by ddziaduch** [comment]
Hi @jails I started working on this last year, but do not have time now to finish this.

We can use https://github.com/rectorphp/rector for this I think

**Comment by jails** [comment]
5.6 and 7.0 has been dropped in the new release.

**Comment by samsonasik** [comment]
@jails the require in composer.json still > 5.5

**Comment by jails** [comment]
Good catch :+1:
