### ISSUE TITLE
Double instance fails on nullable type

### ISSUE THREAD

**Issue by TomPradat** [kahlan/kahlan#326]
Hi, I'm trying to do something like this :

```php
interface FooInterface
{
    public function foo(): ?Foo
}

// Test
$foo = Double::instance(['implements' => FooInterface::class]);
allow($foo)->toReceive('foo')->andReturn(null);

$foo->foo(); // This fails
```
I get a TypeError of this kind :

`Return value of Kahlan\\Spec\\Plugin\\Double\\Double110::foo() must be an instance of Foo, null returned`

This works if i remove the return type of the foo function in the interface.

I'm using php 7.3.4

**Comment by jails** [comment]
Thanks for the detailed example :-1: !
It should have been fixed in the 4.6.2 release.

**Comment by TomPradat** [comment]
I'm still having the issue though (even on master).

**Comment by jails** [comment]
It's working for me. Did you tried to clear the cache after the upgrade `kahlan --cc` ?

**Comment by TomPradat** [comment]
Maybe i'm doing something wrong, but the test fails for me => https://github.com/TomPradat/kahlan-nullable-example

**Comment by jails** [comment]
Ah yeah my bad, I only fixed the issue for built-in types.
It should now work fine with the 4.6.3 release.

**Comment by TomPradat** [comment]
No problem, thank you for your time, everything works for me now :)
