### ISSUE TITLE
add --watch parameter

### ISSUE THREAD

**Issue by phishy** [kahlan/kahlan#328]
Most testing suites have a --watch parameter that will re-run the tests upon file change. Kahlan is amazing, and this would make it even better. :-)

**Comment by jails** [comment]
Thank you !
There's already a lot of JS tools who are handling that very well. Why not simply using them ?
As an example, the watch feature can be done with chokidar like so:

```
npm install chokidar-cli
chokidar -c ./bin/kahlan ./spec/**/*.*
```

Or you can choose the one you are familiar with ?

**Comment by phishy** [comment]
Thanks, I'll use that!
