### ISSUE TITLE
Feature Request : ToThrow check only exception type

### ISSUE THREAD

**Issue by TomPradat** [kahlan/kahlan#332]
I think it would be valuable to be able to pass a string to this method and check that the actual exception has the type excepted.

```php
expect($closure)->toThrow(Exception::class);
```

I think this is valuable because if you have a custom Exception with a mandatory argument in the constructor you need to Double that argument to get this working, which is more painful and kinda useless :

```php
class CustomException extends Exception
{
     public function __construct(CustomClass $class) {}
}

// Right now you need to do this
expect($closure)->toThrow(new CustomException(Double::instance(['extends' => CustomClass::class]));

// But it would be great to be able do this
expect($closure)->toThrow(CustomException::class);
```

Maybe it could have the name `toThrowAnInstanceOf`

**Comment by jails** [comment]
Right now I only implemented the `jasmine.js` matchers. But I guess each developer has it's own need and matchers requirements. To keep the API simple I would prefer to only embed in the core the most used matchers.
For all other matchers there's a dedicated repository https://github.com/kahlan/extra-matcher for developers who have further needs and requires more specific matchers.
