### ISSUE TITLE
Setting a default spec path doesn't work if you specify a config file

### ISSUE THREAD

**Issue by ezzatron** [kahlan/kahlan#335]
I've set up a repo to demonstrate this issue over at [ezzatron/kahlan-repro](https://github.com/ezzatron/kahlan-repro). Steps to reproduce:

1. `composer install`
2. `kahlan` (works)
3. `kahlan --config kahlan-config.php` (does not work, ignores default spec path in config)

Here's the contents of the files involved:

> `kahlan-config.php`
>
> ```php
> <?php
> 
> $commandLine = $this->commandLine();
> $commandLine->option('spec', 'default', 'test');
> ```

> `test/example.spec.php`
>
> ```php
> <?php
>
> describe('Kahlan issue repro', function () {
>     it('runs the specs in a custom path', function () {
>         expect(true)->toBe(true);
>     });
> });
> ```

Output with no `--config` specified:

```
$ kahlan
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The PHP Test Framework for Freedom, Truth and Justice.

src directory  :
spec directory : /Users/erin/grit/github.com/ezzatron/kahlan-repro/test

.                                                                   1 / 1 (100%)



Expectations   : 1 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 1 of 1 PASS in 0.011 seconds (using 2MB)
```

Output with config file specified:

```
$ kahlan --config kahlan-config.php
ERROR: unexisting `spec` directory, use --spec option to set a valid one (ex: --spec=tests).
```

**Comment by jails** [comment]
I think the command line is `kahlan --config=kahlan-config.php` with the `=` operator.

**Comment by ezzatron** [comment]
Ah, right. Sorry, that always catches me out! Works fine using the `=` syntax.
