### ISSUE TITLE
Problem with composer autoload files

### ISSUE THREAD

**Issue by prolic** [kahlan/kahlan#343]
Having this in the projects composer.json

```
"require": {
    "php": "^7.4",
    "phunkie/phunkie": "^0.11.1"
  },
  "require-dev": {
    "kahlan/kahlan": "^4.7.2"
  }
```

and running `vendor/bin/kahlan`

results in this output

```
Notice: Constant Option already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 14
PHP Notice:  Constant ImmList already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 15

Notice: Constant ImmList already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 15
PHP Notice:  Constant ImmSet already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 16

Notice: Constant ImmSet already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 16
PHP Notice:  Constant Function1 already defined in /tmp/kahlan/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 17

Notice: Constant Function1 already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 17
PHP Notice:  Constant _ already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 18

Notice: Constant _ already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 18
PHP Notice:  Constant None already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 19

Notice: Constant None already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 19
PHP Notice:  Constant Nil already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 20

Notice: Constant Nil already defined in /tmp/kahlan/home/prolic/test/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php on line 20
```

**Comment by samsonasik** [comment]
For workaround, I think you can create `kahlan-config.php` file and describe patcher like the following:

```php
<?php // kahlan-config.php

use Kahlan\Filter\Filters;
use Kahlan\Jit\Patcher\Layer;

Filters::apply($this, 'patchers', function($next) {

    $files = $this->autoloader()->files();
    foreach ($files as $key => $file) {
        if ($file === __DIR__ . '/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php') {
            unset($files[$key]);
        }
    }
    $this->autoloader()->files($files);
    \Kahlan\Jit\includeFile(__DIR__ . '/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php');

    return $next();

});
```

I created repository for its temporary workaround https://github.com/samsonasik/kahlan-issue-343

**Comment by samsonasik** [comment]
@jails I created PR #344 could you verify? thank you.

**Comment by prolic** [comment]
Thanks!

**Comment by prolic** [comment]
@samsonasik Using your `kahlan-config.php` file, the line `\Kahlan\Jit\includeFile(__DIR__ . '/vendor/phunkie/phunkie/src/Phunkie/Functions/common.php');` makes problems, if I remove it, it works for me again.

Note: I added more to my `composer.json` like this:

```
"files": [
      "src/Functions/basic_parser.php",
      "src/Functions/php.php"
    ]
```

so maybe that's the reason, using the initial example provided earlier, your suggestion works.

**Comment by samsonasik** [comment]
could you try my branch at https://github.com/kahlan/kahlan/pull/344 ? with point my repo and branch in composer.json

**Comment by samsonasik** [comment]
@prolic fixed in v 4.7.2, please run composer update and clear cache kahlan with run:

```bash
composer update
vendor/bin/kahlan -cc
```

**Comment by samsonasik** [comment]
oh, the tag should be 4.7.3

**Comment by samsonasik** [comment]
@jails seems re-create tag of 4.7.2 ... https://github.com/kahlan/kahlan/commit/025114b7f13985abceff3ba0e28cca71cb0d40e8 

@jails your last commit date is Jan 25, that's weird.

![Screen Shot 2020-04-10 at 9 03 02 PM](https://user-images.githubusercontent.com/459648/78996379-af8b9180-7b6e-11ea-99e9-d609efb1b7d4.png)


@prolic you probably need to clear the composer cache as well.

**Comment by samsonasik** [comment]
@jails oh, I just realize you didn't make a release for it. I will do it.

**Comment by samsonasik** [comment]
@jails I just create a new tag for it 4.7.3 at https://github.com/kahlan/kahlan/releases/tag/4.7.3 .
@prolic please run composer update and vendor/bin/kahlan -cc:

```
composer update && vendor/bin/kahlan -cc
```

**Comment by prolic** [comment]
Thanks @samsonasik - unfortunately this doesn't work at all. All my own autoload-files are ignored now.

My composer.json

```
"require": {
    "php": "^7.4",
    "phunkie/phunkie": "^0.11.1",
    "nette/php-generator": "^3.3.4"
  },
  "require-dev": {
    "kahlan/kahlan": "^4.7.3",
    "prooph/php-cs-fixer-config": "^0.3",
    "satooshi/php-coveralls": "^2.0"
  },
  "autoload": {
    "psr-4": {
      "Fpp\\": "src/"
    },
    "files": [
      "src/Builder/enum.php",
      "src/Functions/basic_parser.php",
      "src/Functions/fpp_parser.php",
      "src/Functions/php.php"
    ]
  }
```

**Comment by prolic** [comment]
However, using the `kahlan-config.php` and 4.7.2 is works correctly now.

**Comment by samsonasik** [comment]
@prolic I created new patch at https://github.com/kahlan/kahlan/pull/345 , could you try update your composer.json with:

```javascript
"kahlan/kahlan": "dev-try-re-fix-343",
```

and try `composer update && vendor/bin/kahlan -cc` ? Thank you ;)

**Comment by samsonasik** [comment]
@prolic could you try update again your composer.json with:

```
"kahlan/kahlan": "dev-try-re-fix-343",
```

and try composer update && vendor/bin/kahlan -cc ? Thank you ;)

**Comment by prolic** [comment]
This seems to work, thanks.

**Comment by samsonasik** [comment]
@prolic thank you for the check. I created new tag 4.7.4 for it ;) https://github.com/kahlan/kahlan/releases/tag/4.7.4

**Comment by prolic** [comment]
Thank you so much for your responsiveness. This really helped me a lot!
