### ISSUE TITLE
[Question] Works only with one class per PHP file?

### ISSUE THREAD

**Issue by thiagodp** [kahlan/kahlan#347]
First of all, good work with Kahlan :)

**Is it possible to create tests for PHP files with more than one class?**

Kahlan appears to not be able to deal with that case.

Example:
```text
 ┃
 ┣ spec/          
 ┃ ┣ Foo.spec.php
 ┃ ┗ MoreThanOneClass.spec.php
 ┣ src/              
 ┃ ┣ Foo.php
 ┃ ┗ MoreThanOneClass.php             🡐 contains classes Bar and Zoo
 ┗ ...
```

- `Foo.spec.php` pass as expected.
- `MoreThanOneClass.spec.php` gives an error when executed:
  ```text
   message:`Error` Code(0) with message "Class 'example\\Bar' not found"
   ```

Using Kahlan 4.7, PHP 7.2 and PSR-4.

**Comment by thiagodp** [comment]
Attaching the example:

[kahkan-test.zip](https://github.com/kahlan/kahlan/files/4545861/kahkan-test.zip)

**Comment by thiagodp** [comment]
Interestingly, if I rename `src/MoreThanOneClass.php` to `src/Bar.php` it works. But if I rename it to `src/Zoo.php`, it doesn't.

Hence, it appears that Kahlan is checking if the file has the same name as its **first class**.

Whether the  first declaration is an `interface`, it doesn't work either.

**Comment by jails** [comment]
Classes are not autoloaded by Kahlan but by Composer. So to have your classes automagically loaded with Composer your file naming convention must follow [PSR-0](https://www.php-fig.org/psr/psr-0/) or [PSR-4](https://www.php-fig.org/psr/psr-4/) to make it work out of the box.
If you don't wan't to follow PSR-0 or PSR-4 you'll need to include all your php files manually on top of spec files through a `require` or `include` statement (like we did before Composer) .

**Comment by thiagodp** [comment]
> Classes are not autoloaded by Kahlan but by Composer.

Ah, right. When I read the docs about Directory Structure (in Getting Started), it seemed like the loading was performed by Kahlan. Specially considering this part:

> The spec directory should mirror the structure of your source code directory.

Thank you.
