### ISSUE TITLE
[Doc] Add `use function` to the examples in order to help code editors

### ISSUE THREAD

**Issue by thiagodp** [kahlan/kahlan#348]
As you known, PHP 5.6 introduced [`use function`](https://www.php.net/manual/pt_BR/language.namespaces.importing.php) to import a function declaration. When the test files do not declare functions such as `describe`, `it`, or `expect`, editors or their plugins (*e.g.*, [Intelephense](https://github.com/bmewburn/vscode-intelephense)) will underline them as if they were `undefined functions`.

Thus, the examples on the documentation could include something like this:
```php
// Declare `use function` only if you are using PHP 5.6+
use function \Kahlan\describe;
use function \Kahlan\it;
use function \Kahlan\expect;
```

The line comment was included since Kahlan supports PHP 5.5.

_Without_ `use function`:

![image](https://user-images.githubusercontent.com/2997844/80497982-8fffb180-8941-11ea-9075-450f90d58a6f.png)

Declaring `use function`:

![image](https://user-images.githubusercontent.com/2997844/80497696-313a3800-8941-11ea-8a3a-d3055385b4cc.png)

**Comment by ddziaduch** [comment]
Seems that this plugin does not work too well, as there is not such problem in PhpStorm.

All the functions are defined in https://github.com/kahlan/kahlan/blob/master/src/functions.php

**Comment by jails** [comment]
Indeed it's probably more an Intelephense issue. Looks like the issue https://github.com/bmewburn/vscode-intelephense/issues/387 hasn't been completly addressed with all composer autoloaded files.

**Comment by futbolsalas15** [comment]
Temporal fix (at least until intelephense fixes the error):

In vs code workspace/user settings level, add the following

```json
{
  "intelephense.environment.includePaths": [
    "./vendor/kahlan/kahlan/src/functions.php"
  ]
}
```
