### ISSUE TITLE
[Question] How to mock a non existing function

### ISSUE THREAD

**Issue by azeemhassni** [kahlan/kahlan#349]
First of all thanks for the nice work, I'm playing with this lib and unable to get the mocks working,

here is what I'm trying

```php
// example.php

function get_something($some_param) {

 $something = query_something($some_param);

 // some magic goes here

return $something;
}

```

And in my test file.
```php
// example.spec.php
describe('get_something', function(){

    beforeAll(function(){
       require "example.php";
    });
    
    describe('given something', function(){
       
        beforeEach(function(){
            $this->something = 'something';
        });
        
        describe('when asked for something', function(){
           
            beforeEach(function(){
               
                // This part is not working, an undefined function error is thrown.
                allow('query_something')->toBeCalled()->andReturn(function(){
                    return 'magic';
                });
                
                $this->magic = get_something($this->something);
            });
            
            it('should return something', function(){
               expect($this->magic)->toBe('something magical'); 
            });
            
        });
        
    });
    
});
```
As you can see the `query_something` function is mocked but I still get an undefined function error.

Any help is appropriated.

**Comment by samsonasik** [comment]
Non existing function can't be stubbed. Also, please read the doc https://kahlan.github.io/docs/allow.html

```
Note: stubs & monkey patching only works for classes loaded by Composer.
```

**Comment by jails** [comment]
Hi,
One of PHP's assumptions is that once you define a function/class it stays defined forever. So the only way for Kahlan to stub or monkey path functions/classes is to perform some "Just In Time" code rewriting during the Composer's classes autoloading step.

So if you try to stub or monkey patch something you `require` inside a spec file it won't get intercepted by JIT patchers and so won't be patched.

Starting 4.1.x, the Kahlan autoloader is initialized earlier and should now be able to patch files loaded in the `composer.json` through the files section:
```php
"autoload": {
  "files": [
    "src/somefilewithcustomfunctions.php"
  ]
}
```

**Comment by azeemhassni** [comment]
> Hi,
> One of PHP's assumptions is that once you define a function/class it stays defined forever. So the only way for Kahlan to stub or monkey path functions/classes is to perform some "Just In Time" code rewriting during the Composer's classes autoloading step.
> 
> So if you try to stub or monkey patch something you `require` inside a spec file it won't get intercepted by JIT patchers and so won't be patched.
> 
> Starting 4.1.x, the Kahlan autoloader is initialized earlier and should now be able to also patch files loaded in the `composer.json` through the files section:
> 
> ```
> "autoload": {
>   "files": [
>     "src/somefilewithcustomfunctions.php"
>   ]
> }
> ```

This was helpful, Thanks @jails
