### ISSUE TITLE
PHP Fatal error:  You need to set `xdebug.coverage_enable = On` in your php.ini. on PHP 8.0

### ISSUE THREAD

**Issue by feryardiant** [kahlan/kahlan#354]
Just experiencing [this error](https://github.com/projek-xyz/container/runs/849643173?check_suite_focus=true#step:8:18) on PHP 8.0, even I manually add the [ini value](https://github.com/projek-xyz/container/runs/847519859?check_suite_focus=true#step:3:21), the error still exists.

I've tried to use `coverage = none` to remove `xdebug`, as stated [here](https://github.com/shivammathur/setup-php#disable-coverage) and expect to see this error

https://github.com/kahlan/kahlan/blob/c529ef24201053ba76d3c8c3531acd76b629ce87/src/Cli/Kahlan.php#L543-L544

But the `xdebug` extension seems still being loaded, so the error remain the same.

The error can simply be fixed by running the test using `phpdbg` to use Kahlan's `phpdbg driver`.

**Comment by jails** [comment]
When you [enable the kahlan's coverage option](https://github.com/projek-xyz/container/blob/master/test/config.php#L11), Kahlan rely on either Xdebug or phpdbg to collect the coverage. So one on them must be available.
PHP 8.0 is still an alpha so I'm not sure [xdebug is yet available](https://xdebug.org/docs/compat) for PHP 8.0, so the only option seems to use phpdbg.

**Comment by feryardiant** [comment]
> PHP 8.0 is still an alpha so I'm not sure [xdebug is yet available](https://xdebug.org/docs/compat) for PHP 8.0, so the only option seems to use phpdbg.

Yes, but the problem here is 

> I've tried to use `coverage = none` to remove `xdebug`, as stated [here](https://github.com/shivammathur/setup-php#disable-coverage) and expect to see this error

I'm still getting

```
PHP Fatal error:  Uncaught RuntimeException: You need to set `xdebug.coverage_enable = On` in your php.ini.
```

instead of 

```
ERROR: PHPDBG SAPI has not been detected and Xdebug is not installed, code coverage can't be used.
```

Which mean, `xdebug` extension is still being loaded.

https://github.com/kahlan/kahlan/blob/c529ef24201053ba76d3c8c3531acd76b629ce87/src/Cli/Kahlan.php#L540-L541

**Comment by jails** [comment]
I don't get it, if xdebug is still loaded, despite the `coverage = none` option, so the issue is related to [this repository](https://github.com/shivammathur/setup-php#disable-coverage) which load xdebug anyway.

**Comment by feryardiant** [comment]
> so the issue is related to this repository

Exactly, 😅
Just want to tell you first before asking them about the issue
