### ISSUE TITLE
Doesn't work when using the keyword "static" in front of function.

### ISSUE THREAD

**Issue by drupol** [kahlan/kahlan#355]
I found out that the following test will work:

```php
<?php

declare(strict_types=1);

namespace App\Spec;

use App\Foo;

describe('Foo', function () {
    describe('get', function ()  {
        it('foobar', function () {
            $foo = new Foo();

            expect($foo->get())->toEqual('foo');
        });
    });
});
```

However, this one won't work:

```php
<?php

declare(strict_types=1);

namespace App\Spec;

use App\Foo;

describe('Foo', static function () {
    describe('get', static function ()  {
        it('foobar', static function () {
            $foo = new Foo();

            expect($foo->get())->toEqual('foo');
        });
    });
});
```

This is just because of the keyword `static` in front of function.

Is it an intended behavior ?

Thanks.

**Comment by jails** [comment]
It's related to Kahlan's behavior. all specs function are attached to an instance which inherits properties values from its parents so you can use `$this` to access parents' values ([see "Variable scope" in the documentation](https://kahlan.github.io/docs/dsl.html)).

**Comment by drupol** [comment]
Make sense now, thanks !
