### ISSUE TITLE
migrate to travis-ci.com or github action

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#358]
@jails travis-ci.org will be shutdown in several weeks, ref https://travis-ci.org/

```
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. 
```

The option can be 2:

- migrate to travis-ci.com
- migrate to github action

what do you think?

**Comment by jails** [comment]
I think I already moved the repository to [travis.com](https://travis-ci.org/github/kahlan/kahlan), but indeed I need to update the README.md to update the link.

**Comment by jails** [comment]
fixed in https://github.com/kahlan/kahlan/commit/32035b2b3d6517665fb831add4b2682d35770717
