### ISSUE TITLE
Unable to run Kahlan under PHP 8 + GitHub Actions

### ISSUE THREAD

**Issue by ezzatron** [kahlan/kahlan#359]
I was attempting to prepare a new release of [`phony-kahlan`](https://github.com/eloquent/phony-kahlan) with support for PHP 8 but I've run into an issue that only seems to manifest when running under GitHub Actions. When I run the test suite locally, there are no issues.

The problem I'm seeing is related to Kahlan's class loader somehow:

```
[Uncaught Error in /tmp/kahlan/home/runner/work/phony-kahlan/phony-kahlan/vendor/eloquent/phony/src/initialize.php on line 10]
Error: Class "FacadeContainer" not found in /tmp/kahlan/home/runner/work/phony-kahlan/phony-kahlan/vendor/eloquent/phony/src/initialize.php:10
Stack trace:
#0 /home/runner/work/phony-kahlan/phony-kahlan/vendor/kahlan/kahlan/src/Jit/ClassLoader.php(251): require()
#1 /home/runner/work/phony-kahlan/phony-kahlan/vendor/kahlan/kahlan/bin/kahlan(57): Kahlan\Jit\ClassLoader->loadFile()
#2 {main}
```

Under PHP 7.3 and 7.4, the issue does not occur, only under PHP 8.0 and beyond. You can see a relevant GHA run at https://github.com/eloquent/phony-kahlan/actions/runs/437475374

It's worth noting that my Kahlan config is set up to bypass monkey-patching altogether, so I'm not sure exactly what's going on here:

```php
<?php // kahlan-config.php

$commandLine = $this->commandLine();
$commandLine->option('spec', 'default', 'test/suite');
$commandLine->set('include', []);

```

**Comment by jails** [comment]
Lot of changes has been introduced in PHP 8.0.
Would you mind testing the 5.0.0 version ?

**Comment by ezzatron** [comment]
Looks to be resolved in `5.x`. Thanks!
