### ISSUE TITLE
How to test if a function is never called ?

### ISSUE THREAD

**Issue by piolet** [kahlan/kahlan#365]
Hello

Is there a way to verify that a method in a class is never called?

For example:
`expect(Filesystem::class)->toReceive('listContents')->with("/")->times(0);`

or 

`expect(Filesystem::class)->toReceive('listContents')->with("/")->neverCalled();`

**Comment by puniserv** [comment]
`
            expect(Filesystem::class)->not->toReceive('listContents')->with("/")
`

**Comment by piolet** [comment]
thx
