### ISSUE TITLE
Can i Stub an Exception ?

### ISSUE THREAD

**Issue by piolet** [kahlan/kahlan#366]
Hello,

Is it possible to simulate an exception when calling a function.
For example, it is possible to simulate an exception when calling a function:

`Stub::on(MyClass::class)->method('myFunction')->andThrow(new MyException);`

To be able to simulate the try catch and thus pass through all the branches of the code

I just, in the documentation, could check that a result was an exception, but I didn't see how to simulate an exception.

**Comment by puniserv** [comment]
`->andRun(function() { throw new MyException; });

`

**Comment by piolet** [comment]
Super

thx again
