### ISSUE TITLE
"transient" ParseError with Guzzle's CurlMultiHandler, StreamHandler, Promise on PHP 8 w/ Kahlan 5

### ISSUE THREAD

**Issue by adamcameron** [kahlan/kahlan#370]
This is an odd one. Firstly there's a github repo to help reproduce the issue here: https://github.com/adamcameron/kahlanIssue, and the readme.md has a full explanation. As does http://blog.adamcameron.me/2021/02/troubleshooting-issue-with-kahlan.html.

I have a test that uses Guzzle to curl example.com, and the test examines the content. Don't worry about the nature of the test, that's just something to reproduce the issue.

When I run the test I get this error:
```
ParseError` Code(0) with message "Unclosed '{' on line 142 does not match ')'"
vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php, line  to 158
```
If I modify that file with code changes, and rerun, the error moves on to:

```
`vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php` line 201
```

And after touching that file, it moves a third time to `vendor/guzzlehttp/promises/src/Promise.php line 151`.

After touching those three files, the tests run. If I blow-away vendor and re-run the tests: no problem. Which is quite odd.

I know those are all Guzzle files, but If I run the equivalent code in PHPUnit, there is never any issue, hence me doubting it's anything to do with Guzzle specifically, it's how Kahlan *is calling* Guzzle. Probably with vendor/kahlan/kahlan/src/Jit/ClassLoader.php, which is the preceding file in the callstack, each time. I have to admit I did not look into that file to see what it is doing. I'll crack on with that shortly.

If I relocate the app to a different file system location entirely (say from C:\src\kahlanIssue to C:\temp\kahlanIssue), the problem recurs, with the same remedial action.

Reproduced it on Ubuntu-on-Docker, Ubuntu-on-WSL, and native Windows. On two different machines.

Retrograding to PHP 7.4, and issue goes away. 

Let me know if you need me to check anything else.

Cheers!

**Comment by adamcameron** [comment]
OK I see where you're going wrong (but am not looking further into *why* you're going wrong). See attached
[CurlMultiHandler.php.txt](https://github.com/kahlan/kahlan/files/6022420/CurlMultiHandler.php.txt) and 
[CurlMultiHandler.munged.php.txt](https://github.com/kahlan/kahlan/files/6022421/CurlMultiHandler.munged.php.txt)

Original code, down at 157-158:
```
        // Step through the task queue which may add additional requests.
        P\Utils::queue()->run();
```
And your monkey-patching does this:
```
        // Step through the task queue which may add additional requests.($__KMONKEY__396__?$__KMONKEY__396__:
        $__KMONKEY__396::queue())->run();
```

Looks like you have an off-by-one error there as to where you start your monkey patching? It can't just be a mishandling of code following a single-line comment, or you'd get it more often.

Is it a mishandling of single-char namespaces?

Anyway, hopefully that gives you enough to work on.

**Comment by jails** [comment]
Thank you for the detailled use case and investigations :+1: 
I'll dig in.

**Comment by adamcameron** [comment]
And on PHP 7.4 it's this:

```
       // Step through the task queue which may add additional requests.
($__KMONKEY__396__?$__KMONKEY__396__:        $__KMONKEY__396::queue())->run();
```

Just that missing linefeed, eh? Anyhow, I'll leave ya to it. Thanks for looking.

**Comment by jails** [comment]
Indeed, looks like it's something that has been introduced in [PHP8 as a BC break](https://www.php.net/manual/fr/migration80.incompatible.php)

`T_COMMENT tokens will no longer include a trailing newline. The newline will instead be part of a following T_WHITESPACE token. It should be noted that T_COMMENT is not always followed by whitespace, it may also be followed by T_CLOSE_TAG or end-of-file.`

I'll probably need to fix the Kahlan parser somehow.

**Comment by jails** [comment]
fixed in the 5.0.8 release.

**Comment by adamcameron** [comment]
That is amazingly quick! I shall test it this evening. Got homework to supervise & child to feed first :-)

**Comment by adamcameron** [comment]
Confirmed: fixed. Thanks!

**Comment by jails** [comment]
Cool :+1:
