### ISSUE TITLE
focused mode exits with -1/255

### ISSUE THREAD

**Issue by adamcameron** [kahlan/kahlan#372]
Hi
I have a spec that I am using focused-mode on (ie: `fdescribe`). This works fine, but when I run the tests (`vendor\bin\kahlan`) it exits with `-1` (which to bash is interpreted as `255` as `-1` isn't valid). A coupla things here;

* a non-zero exit code suggests something went wrong. However this is not a case of something being wrong. The test run did exactly what it was supposed to do. That "what it was supposed to do" is "skip a lot of tests" is not indicative of something going wrong.
* As above, I'm not sure `-1` is a good exit code to use, the first point notwithstanding.
* Exit code usage has recommendations (eg: https://tldp.org/LDP/abs/html/exitcodes.html), which suggest user-world should restrict itself to 64 - 113.
* There's no mention in the docs for focus-mode indicating it results in a non-zero exit code. And I can't find any other documentation that detail any non-zero exit codes being used by Kahlan.
* This all "fails" silently when running `vendor/bin/kahlan` (which is cool: it's not really a failure), but if I run it via a composer script, Composer - correctly - flags it up as a problem: "Script vendor/bin/kahlan handling the spec event returned with error code 255" (in bright red! ;-)

I'm not sure how much of an issue this is. Now that I know what's going on I'm just gonna shrug and yeah, NP. And it didn't take me long to work out what was going on, so presume other devs' experiences will be the same if they notice this.

**Comment by jails** [comment]
This behavior has been added in Jasmine in order to help users find times when they had accidentally commited their suite with an fit or fdescribe and inadvertently disabled the rest of their specs. I ported this behavior to Kahlan to match Jasmine behavior.
Indeed I didn't notice it returns -1 on errors, I think 1 should be just fine.

**Comment by jails** [comment]
Fixed in https://github.com/kahlan/kahlan/commit/d3f35b2fa573e8f7d37751382444154eb0f9e409
