### ISSUE TITLE
Bug(?): Double::instance doesn't seem to cater to stubbing methods with return-types

### ISSUE THREAD

**Issue by adamcameron** [kahlan/kahlan#377]
Code will probably explain it:

```
class SomeClass {
	public function stubMe() : array {
		return ['real value'];
	}
}

// ...

$double = Double::instance(['extends' => SomeClass::class, 'methods' => 'stubMe']);
allow($double)->toReceive('stubMe')->andReturn(['stubbed value']);
```

Results in: 
```
Fatal error: Declaration of Kahlan\Spec\Plugin\Double\Double2::stubMe() must be compatible with SomeClass ::stubMe(): array in vendor/kahlan/kahlan/src/Plugin/Double.php(104) : eval()'d code on line 6
```

If I take the return type off `stubMe` it all works fine.

**Comment by jails** [comment]
The `'methods'` options creates new "virtual method stubs" so you don't need it here.
```php
$double = Double::instance(['extends' => SomeClass::class]);
allow($double)->toReceive('stubMe')->andReturn(['stubbed value']);
```

**Comment by adamcameron** [comment]
Without specifying `'methods' => 'stubMe'`, `subMe` was not stubbed at all. I realise this is contrary to the docs, but this was my experience. That is perhaps a separate issue again. I was gonna look more into it, but currently I am spending more time looking at Kahlan code than I am writing my own code, and - to be frank - I'm a bit over it. I am currently porting my testing back to PHPUnit I'm afraid :-(

**Comment by jails** [comment]
Glad you find the tool which fit you more 👍

**Comment by adamcameron** [comment]
Not sure why you closed this: the issue still stands and is still a bug, whether or not it's going to impact *me* any more. It should be left open until such time (which might be never: cool) as it's addressed.

**Comment by jails** [comment]
I closed it because I wasn't able to reproduce it.
The test I used: https://github.com/kahlan/kahlan/commit/2175d99078b7339bce946df59d43cbd7d307115e
The Result: https://travis-ci.com/github/kahlan/kahlan/builds/219197349

Kahlan doubles works with Kahlan's Just In Time  patching but without a github repo with a fully reproductible example + configuration files it's kindda hard to guess problems.

**Comment by adamcameron** [comment]
That test isn't addressing the issue. I think you have got distracted by the `methods` thing you mentioned, which is nothing to do with this. That's a _separate_ issue. Let's just focus on *this* issue, which - as per the title of the issue - is (my **emphasis**):

> Double::instance doesn't seem to cater to stubbing **methods with return-types**

And as per my example code:

```
public function stubMe() : array { // <--- IT HAS A RETURN TYPE
	return ['real value'];
}
```

The method your test is stubbing - `Doz:foo2` - *doesn't* have a return type:

```
class Doz
{
    // ...
    public function foo2($b = null) // <--- NO RETURN TYPE
    {
    }
    // ...
```

As for expecting a whole repo etc to demonstrate a pretty obvious issue, I think that's egregious. You could copy and paste the code gave you into your `Doz` class and into its spec and run it and see the issue. If you _can't_ see the issue, then let's start talking about vagaries of config & environment then. 

However the code that's causing the problem seems to be this:

```
$result[$name] = "public {$static}function {$name}() {{$return}}";
```

(line 287 of Double). 

It is not catering for the method's return type. [shrug]

I don't think you need a special github repo to be able to demonstrate this issue to yourself. The info I gave you initially _ought to be_ enough? At least try it. That's why I gave it to you.

Let me know if not, and what additional info you need.

**Comment by jails** [comment]
`You could copy and paste the code gave you into your Doz class and into its spec and run it and see the issue. If you can't see the issue, then let's start talking about vagaries of config & environment then`.

Man... it's not me who have a problem with Kahlan. People here are generously giving their free time to help people with issues on kahlan. So the least that you can do is to make things easier for everyone (and not just me) so everybody can help without to wasting their time with guessing.

So I'm probably too stupid to understand the pretty obvious but it still can't reproduce it.
The test I used: https://github.com/kahlan/kahlan/commit/cc986b74ea490d69fde72150245799228dbe15ec
The Result: https://travis-ci.com/github/kahlan/kahlan/builds/219203750

Anyhow without a github repo I'm done with copy/paste and guesses...

**Comment by adamcameron** [comment]
OK, "the plot thickens" as the overused trope goes.

* I cannot replicate this on native Windows;
* I cannot replicate this on Ubuntu running via WSL on that same Windows box;
* I *can* replicate it in a Docker container running from the Ubuntu distro mentioned above.

(and same with issue 380).

I am still running the tests within the codebase of a larger app (so with a bunch of other composer dependencies installed etc), but I don't see how that - per se - would impact proceedings. I cannot at the moment put over more time into investigating this, but can perhaps return to it Mon evening. I can try spinning up the container with just the test code in it, as a start. If I manage to do this, I will report back.

Editorial observations:
* Jails... I am sinking quite a bit of my own time into assessing these issues (before I even raise them, and then afterwards in this back & forth, and with my own separate investigations). I've probably spent a day on all the various bits and bobs I've raised with you so far. This time is to benefit *you* (ie: Kahlan), not me. Perhaps think about that before making comments about who is wasting whose time, yeah? I'm *trying* to work with you here to improve your software. I do not benefit from this. I'm happy to try to help, but less so when you start to have a go at me like you did above.
* That you can run a repro case and not see the same issues I am is just "it works OK on my machine". Absence of evidence is not evidence of absence. Let's not worry so much about where/why/how the code *does* work, and focus on working out why the code sometimes *doesn't* work. I'm not lying about this, after all: I am def seeing the errors on the screen, and with the exact code I provided above. It's clear that neither of us completely understand what's up, and it could well end up be me doing something daft (I am a noob with Kahlan after all). Given I'm the noob and you're the expert... maybe you could lead me in a direction that might be a sensible approach to investigate. But "it works OK on my machine [shrug]" is not helpful here.

**Comment by adamcameron** [comment]
I've found the "cause" of this. It is a symptom of my attempt to work-around issue #380, and is probably not an issue in and of itself (and directly related to what you said about using `methods` here).

I can replicate #380 at will now, and have found the cause, and have attached a repro case to that.

Happy to leave this one closed.
