### ISSUE TITLE
Documented way of disabling patching doesn't work

### ISSUE THREAD

**Issue by adamcameron** [kahlan/kahlan#378]
Hi
The docs say this:
```
Finally, you can disable all the patching if you prefer to deal with DI only and are not interested by Kahlan's features:

$this->commandLine()->set('include', []);
```

Here's a test demonstrating this doesn't work:

```
root@5f9133aa9de3:/usr/share/fullstackExercise# cat kahlan-config.php
<?php
$commandLine = $this->commandLine();
$commandLine->option('no-header', 'default', 1);

$this->commandLine()->set('include', []); # SO INCLUDE NOTHING


root@5f9133aa9de3:/usr/share/fullstackExercise# ll /tmp/
total 12
drwxrwxrwt 1 root root 4096 Mar  6 10:30 ./
drwxr-xr-x 1 root root 4096 Mar  6 09:55 ../
drwxr-xr-x 5 root root 4096 Mar  4 01:01 pear/ 

root@5f9133aa9de3:/usr/share/fullstackExercise# # NO KAHLAN CACHE DIR HERE


root@5f9133aa9de3:/usr/share/fullstackExercise# # RUN A TEST
root@5f9133aa9de3:/usr/share/fullstackExercise# vendor/bin/kahlan --spec=spec/integration/baselineDatabase.spec.php --ff  --coverage=1
[successful results elided to save space]

root@5f9133aa9de3:/usr/share/fullstackExercise# ll /tmp/kahlan/usr/share/fullstackExercise/
total 12
drwxr-xr-x 3 root root 4096 Mar  6 10:30 ./
drwxr-xr-x 3 root root 4096 Mar  6 10:30 ../
drwxr-xr-x 6 root root 4096 Mar  6 10:30 vendor/ # OK SO IT'S STILL PATCHING STUFF


root@5f9133aa9de3:/usr/share/fullstackExercise# head --lines 1 /tmp/kahlan/usr/share/fullstackExercise/vendor/symfony/deprecation-contracts/function.php
<?php $__KMONKEY__210=\Kahlan\Plugin\Monkey::patched(__NAMESPACE__ , null, 'function_exists', $__KMONKEY__210__); ?><?php

# MONKEYS EVERYWHERE
```

If I've switched off patching... why is it still MONKEYing with stuff?

I arrived at this because something Kahlan is doing when it's patching autoload files is screwing them up, and causing errors (trying to come up with decent demonstration of that for another issue I need to raise. Sigh).

Given I absolutely do not want Kahlan messing with anything at all in my vendor directory, I first tried just actively including the namespaces I *might* want to patch, hoping that list would be exclusive (ie: only the stuff in the list gets patched, everything else does not), but that didn't work. So I've tried to disable all patching for now... still doesn't work.

As was as this being an issue, can you pls advise if there's another way to reallyreally stop Kahlan trying to monkey with stuff? This current situation is a show-stopper for me.

**Comment by jails** [comment]
Starting 4.1.x, the Kahlan autoloader is initialized earlier and should now be able to also patch files loaded in the `composer.json` through the files section:
```php
"autoload": {
  "files": [
    "src/somefilewithcustomfunctions.php"
  ]
}
```

So to be able to catch such things, the autoloader is started here https://github.com/kahlan/kahlan/blob/master/bin/kahlan#L18

And the configuration is applied there https://github.com/kahlan/kahlan/blob/master/bin/kahlan#L45

So indeed, if between this two points some classes are autoloaded (because of the autoload "files" definition I guess), indeed some files may be catched by the Kahlan JIT autoloader.

**Comment by samsonasik** [comment]
I am closing it as answered.
