### ISSUE TITLE
toBeCalled within Class Static Methods

### ISSUE THREAD

**Issue by devsrealm** [kahlan/kahlan#394]
Say, I have a class has such:

```
class NumberOne
{
 Use ATrait

public static function callmethodintrait()
{
   $store = $this->fromtrait();
   ...more function calls
    $this->finalizeOp();
}
}
```

How can I use toBeCalled on the method fromtrait()?

This is what I am currently trying:

```
$numberOne = new NumberOne(); 
allow('fromtrait')->toBeCalled();
expect('fromtrait')->toBeCalled()->once();
$numberOne ->finalizeOp();
```

which is not working, hopefully waiting for your reply.

Also, toThrow() doesn't work, maybe the issues are  linked, I am using composer and I have dump-autoload several times.

**Comment by samsonasik** [comment]
first, you need to pass class name or object on allow, not direct method, next, follow the docs for call static https://kahlan.github.io/docs/allow.html
