### ISSUE TITLE
Process exit with code 1 in github action

### ISSUE THREAD

**Issue by viduc** [kahlan/kahlan#402]
Hi,

I try to configure github action for my project.
I try to execute codecoverage and the process return error:

`Error: Process completed with exit code 1.`

this my php.xml:
`name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.0', '8.1' ]
    steps:
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-versions }}"
        coverage: xdebug

    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test suite
      run: ./vendor/bin/kahlan --reporter=verbose --coverage=4 --clover=clover.xml`

when i execute kahlan in local i dont have any problem. 

Did you have an idea?

Thanks

**Comment by samsonasik** [comment]
I can't reproduce by re-trigger CI on my module https://github.com/samsonasik/ForceHttpsModule/actions/runs/3472603215/jobs/5803645262 which seems working OK.

You can see my config https://github.com/samsonasik/ForceHttpsModule/blob/master/.github/workflows/ci_build.yml

**Comment by viduc** [comment]
Thanks for your help, i think my problem is right access to some folder and root folder.
