### ISSUE TITLE
PHP 8.2: dynamic properties

### ISSUE THREAD

**Issue by yitznewton** [kahlan/kahlan#404]
There are 3 dynamic properties in `\Kahlan\Jit\Parser` which are throwing (or potentially throwing) deprecation errors in PHP 8.2: 

* `_T_ARROW_FUNCTION`
* `_T_DOUBLE_ARROW`
* `_T_ATTRIBUTE`

**Comment by samsonasik** [comment]
Could you try provide a patch for it? Send to dev branch

**Comment by yitznewton** [comment]
I have the changes in cppgh/kahlan on `master`; there were some seemingly
-unrelated failures in the build which kept me from opening a PR
immediately
