### ISSUE TITLE
Multiple _T_ATTRIBUTE tokens in single line

### ISSUE THREAD

**Issue by michalfelski** [kahlan/kahlan#418]
After fix for multiline PHP8 attributes introduced in 5.2.4, generated code is not patched when it includes multiple attributes in single line.

btw. even before the change, code after attribute could not be patched as it always parses attribute token to the end of line

Since 5.2.4, whole the following code after $author property is parsed as an Attribute

```PHP
class MyClass
{
    #[Column] public int $id;
    #[Column] #[Length(min: 3, message: 'Too short')] public string $author;

    ....

}
```

To resolve it I suggest to not check EOL in the attribute parser. Pull request https://github.com/kahlan/kahlan/pull/419

More over, parameters attributes seems to be not parsed at all, but it is not an issue for now
```PHP
function myFunction(#[Param] $param1, #[Param] $param2) {
    ...
}
```

**Comment by samsonasik** [comment]
Resolved at https://github.com/kahlan/kahlan/pull/419
