### ISSUE TITLE
Bug: toHaveLength() does not work with accented letters and multi-byte strings

### ISSUE THREAD

**Issue by thiagodp** [kahlan/kahlan#420]
These tests fail with Kahlan:
```php
...
        it("passes with accented letters", function () {
            expect('Olá')->toHaveLength(3);
        });

        it("passes with multibyte characters, like emojis", function () {
            expect('Hello 😉')->toHaveLength(7);
        });
```
I'll submit a PR with the fix.

**Comment by jails** [comment]
Thank you for the PR but as explained in https://github.com/kahlan/kahlan/pull/421, `toHaveLength()` return the number of bytes of a string which is independant of the interpretation of the using encoding system.
