### ISSUE TITLE
Bug on Windows

### ISSUE THREAD

**Issue by thiagodp** [kahlan/kahlan#428]
Error while trying to install Kahlan `5.2.7` on Windows 11:

```bash
composer require kahlan/kahlan --dev
```

![image](https://github.com/user-attachments/assets/b8a7a811-d17f-414b-abfb-8c5fab2d61d1)

**Notes:**
1. The same error occurred on other machines with similar environments and also using Windows 10.
2. The same error occurred in projects with no dependencies, but Kahlan.
3.  Adding `--prefer-source` to the installation command make it work. However, this is an annoying, since many other projects are getting the same error. All the other packages (but Kahlan's) install successfully.

**Comment by samsonasik** [comment]
it probably composer cache issue, did you try:

```
composer clear-cache
```

I don't use windows so I am not sure if I can help, but you may can configure in composer.json if the issue persist:

```json
 "config": {
    "preferred-install": {
        "kahlan/kahlan": "source",
        "*": "dist"
    }
 },
```

to only install by source for kahlan.

**Comment by thiagodp** [comment]
Hello @samsonasik, thank you for the feedback.
Unfortunately clearing the cache didn't solve the problem:

![image](https://github.com/user-attachments/assets/77176f79-4248-4ced-8b80-c1b434efdf31)

**Comment by thiagodp** [comment]
When I tried to install Kahlan under Ubuntu on Windows Subsystem for Linux (WSL), it informed that the `zip` extension is **required**.

![image](https://github.com/user-attachments/assets/0695c7ef-8e75-4a71-bd22-e1e446b66b8f)

Adding the zip extension (`sudo apt install php-zip`) solved the problem.
So I figured out that on Windows 10/11 the problem could be the same. And it was.
Enabling the `zip` extension in the `php.ini` file made it to work.

Therefore it may be a good idea to add the `zip` extension to the `require` section of Kahlan's `composer.json`:

```json
"require": {
    "php": ">=7.2",
    "ext-zip": "*"
}
```

**Comment by samsonasik** [comment]
I am not sure, probably @jails know about it, I think for your use case, install `zip` extension is the way

**Comment by thiagodp** [comment]
It seems that the problem occurs because of the _symbolic link_ at `spec/Fixture/Dir/Extensions/Childs`.
A non-administrator user cannot create a symbolic link on Windows.
Therefore, when the installation occurs, Composer cannot create `Childs`.

**Comment by samsonasik** [comment]
Ok, I think the solution is exclude `spec` directory from shipped vendor, by register to `.gitattributes`, something like:

```js
# file .gitattributes

/.gitattributes export-ignore
/spec export-ignore
```

could you create a PR for it? Thank you.

**Comment by samsonasik** [comment]
should be fixed at https://github.com/kahlan/kahlan/pull/429

please clear vendor and run composer update

```
rm -rf vendor/kahlan

composer require --dev kahlan/kahlan:^5.2.8
```

**Comment by thiagodp** [comment]
Thank you @samsonasik 
Version [5.2.8](https://github.com/kahlan/kahlan/releases/tag/5.2.8) installs successfully with the `zip` extension **disabled** 🎉
